/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {88, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};
static const casadi_int casadi_s5[3] = {21, 1, 1};
static const casadi_int casadi_s6[57] = 
  {21, 21, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 15, 19,
  23, 27, 28, 29, 30, 31, 32, 33,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12, 13, 14, 11,
  12, 13, 14, 11, 12, 13, 14, 11,
  12, 13, 14, 15, 16, 17, 18, 19,
  20};

/* BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess:(i0[13],i1[8],i2[],i3[13],i4[88])->(o0,o1[21],o2[21x21,33nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55;
  a00=120.;
  a01=5.0000000000000000e-01;
  a02=arg[0]? arg[0][0] : 0;
  a03=arg[3]? arg[3][0] : 0;
  a02=(a02-a03);
  a03=(a01*a02);
  a03=(a00*a03);
  a04=(a03*a02);
  a05=arg[0]? arg[0][1] : 0;
  a06=arg[3]? arg[3][1] : 0;
  a05=(a05-a06);
  a06=(a01*a05);
  a06=(a00*a06);
  a07=(a06*a05);
  a04=(a04+a07);
  a07=150.;
  a08=arg[0]? arg[0][2] : 0;
  a09=arg[3]? arg[3][2] : 0;
  a08=(a08-a09);
  a09=(a01*a08);
  a09=(a07*a09);
  a10=(a09*a08);
  a04=(a04+a10);
  a10=100.;
  a11=arg[3]? arg[3][4] : 0;
  a12=arg[0]? arg[0][3] : 0;
  a13=casadi_sq(a12);
  a14=arg[0]? arg[0][4] : 0;
  a15=casadi_sq(a14);
  a13=(a13+a15);
  a15=arg[0]? arg[0][5] : 0;
  a16=casadi_sq(a15);
  a13=(a13+a16);
  a16=arg[0]? arg[0][6] : 0;
  a17=casadi_sq(a16);
  a13=(a13+a17);
  a13=sqrt(a13);
  a17=(a12/a13);
  a18=(a11*a17);
  a19=arg[3]? arg[3][3] : 0;
  a20=(a14/a13);
  a21=(a19*a20);
  a18=(a18-a21);
  a21=arg[3]? arg[3][5] : 0;
  a22=(a16/a13);
  a23=(a21*a22);
  a18=(a18-a23);
  a23=arg[3]? arg[3][6] : 0;
  a24=(a15/a13);
  a25=(a23*a24);
  a18=(a18+a25);
  a25=(a10*a18);
  a26=2.;
  a18=(a26*a18);
  a27=(a25*a18);
  a28=(a11*a22);
  a29=(a19*a24);
  a28=(a28-a29);
  a29=(a21*a17);
  a28=(a28+a29);
  a29=(a23*a20);
  a28=(a28-a29);
  a29=(a10*a28);
  a28=(a26*a28);
  a30=(a29*a28);
  a27=(a27+a30);
  a30=(a21*a20);
  a31=(a19*a22);
  a32=(a11*a24);
  a31=(a31+a32);
  a30=(a30-a31);
  a31=(a23*a17);
  a30=(a30+a31);
  a31=(a00*a30);
  a30=(a26*a30);
  a32=(a31*a30);
  a27=(a27+a32);
  a04=(a04+a27);
  a27=arg[0]? arg[0][7] : 0;
  a32=arg[3]? arg[3][7] : 0;
  a27=(a27-a32);
  a32=(a01*a27);
  a32=(a32*a27);
  a33=arg[0]? arg[0][8] : 0;
  a34=arg[3]? arg[3][8] : 0;
  a33=(a33-a34);
  a34=(a01*a33);
  a34=(a34*a33);
  a32=(a32+a34);
  a34=arg[0]? arg[0][9] : 0;
  a35=arg[3]? arg[3][9] : 0;
  a34=(a34-a35);
  a35=(a01*a34);
  a35=(a35*a34);
  a32=(a32+a35);
  a04=(a04+a32);
  a32=arg[0]? arg[0][10] : 0;
  a35=arg[3]? arg[3][10] : 0;
  a32=(a32-a35);
  a35=(a01*a32);
  a36=(a01*a35);
  a36=(a36*a32);
  a32=arg[0]? arg[0][11] : 0;
  a37=arg[3]? arg[3][11] : 0;
  a32=(a32-a37);
  a37=(a01*a32);
  a38=(a01*a37);
  a38=(a38*a32);
  a36=(a36+a38);
  a38=arg[0]? arg[0][12] : 0;
  a32=arg[3]? arg[3][12] : 0;
  a38=(a38-a32);
  a32=(a01*a38);
  a39=(a01*a32);
  a39=(a39*a38);
  a36=(a36+a39);
  a04=(a04+a36);
  a36=1.0000000000000001e-01;
  a39=arg[1]? arg[1][0] : 0;
  a38=(a01*a39);
  a38=(a36*a38);
  a40=(a38*a39);
  a41=arg[1]? arg[1][1] : 0;
  a42=(a01*a41);
  a42=(a36*a42);
  a43=(a42*a41);
  a40=(a40+a43);
  a43=arg[1]? arg[1][2] : 0;
  a44=(a01*a43);
  a44=(a36*a44);
  a45=(a44*a43);
  a40=(a40+a45);
  a45=arg[1]? arg[1][3] : 0;
  a46=(a01*a45);
  a46=(a36*a46);
  a47=(a46*a45);
  a40=(a40+a47);
  a47=arg[1]? arg[1][4] : 0;
  a48=(a01*a47);
  a48=(a36*a48);
  a49=(a48*a47);
  a40=(a40+a49);
  a49=arg[1]? arg[1][5] : 0;
  a50=(a01*a49);
  a50=(a36*a50);
  a51=(a50*a49);
  a40=(a40+a51);
  a51=arg[1]? arg[1][6] : 0;
  a52=(a01*a51);
  a52=(a36*a52);
  a53=(a52*a51);
  a40=(a40+a53);
  a53=arg[1]? arg[1][7] : 0;
  a54=(a01*a53);
  a54=(a36*a54);
  a55=(a54*a53);
  a40=(a40+a55);
  a04=(a04+a40);
  if (res[0]!=0) res[0][0]=a04;
  a39=(a36*a39);
  a39=(a01*a39);
  a38=(a38+a39);
  if (res[1]!=0) res[1][0]=a38;
  a41=(a36*a41);
  a41=(a01*a41);
  a42=(a42+a41);
  if (res[1]!=0) res[1][1]=a42;
  a43=(a36*a43);
  a43=(a01*a43);
  a44=(a44+a43);
  if (res[1]!=0) res[1][2]=a44;
  a45=(a36*a45);
  a45=(a01*a45);
  a46=(a46+a45);
  if (res[1]!=0) res[1][3]=a46;
  a47=(a36*a47);
  a47=(a01*a47);
  a48=(a48+a47);
  if (res[1]!=0) res[1][4]=a48;
  a49=(a36*a49);
  a49=(a01*a49);
  a50=(a50+a49);
  if (res[1]!=0) res[1][5]=a50;
  a51=(a36*a51);
  a51=(a01*a51);
  a52=(a52+a51);
  if (res[1]!=0) res[1][6]=a52;
  a53=(a36*a53);
  a53=(a01*a53);
  a54=(a54+a53);
  if (res[1]!=0) res[1][7]=a54;
  a02=(a00*a02);
  a02=(a01*a02);
  a03=(a03+a02);
  if (res[1]!=0) res[1][8]=a03;
  a05=(a00*a05);
  a05=(a01*a05);
  a06=(a06+a05);
  if (res[1]!=0) res[1][9]=a06;
  a08=(a07*a08);
  a08=(a01*a08);
  a09=(a09+a08);
  if (res[1]!=0) res[1][10]=a09;
  a31=(a26*a31);
  a30=(a00*a30);
  a31=(a31+a30);
  a30=(a23*a31);
  a29=(a26*a29);
  a28=(a10*a28);
  a29=(a29+a28);
  a28=(a21*a29);
  a30=(a30+a28);
  a25=(a26*a25);
  a18=(a10*a18);
  a25=(a25+a18);
  a18=(a11*a25);
  a30=(a30+a18);
  a18=(a30/a13);
  a12=(a12+a12);
  a28=(a24/a13);
  a09=(a23*a25);
  a08=(a11*a31);
  a06=(a19*a29);
  a08=(a08+a06);
  a09=(a09-a08);
  a08=(a28*a09);
  a06=(a22/a13);
  a05=(a11*a29);
  a03=(a19*a31);
  a05=(a05-a03);
  a03=(a21*a25);
  a05=(a05-a03);
  a03=(a06*a05);
  a08=(a08+a03);
  a03=(a20/a13);
  a31=(a21*a31);
  a29=(a23*a29);
  a31=(a31-a29);
  a25=(a19*a25);
  a31=(a31-a25);
  a25=(a03*a31);
  a08=(a08+a25);
  a25=(a17/a13);
  a29=(a25*a30);
  a08=(a08+a29);
  a29=(a13+a13);
  a08=(a08/a29);
  a02=(a12*a08);
  a02=(a18-a02);
  if (res[1]!=0) res[1][11]=a02;
  a02=(a31/a13);
  a14=(a14+a14);
  a54=(a14*a08);
  a54=(a02-a54);
  if (res[1]!=0) res[1][12]=a54;
  a54=(a09/a13);
  a15=(a15+a15);
  a53=(a15*a08);
  a53=(a54-a53);
  if (res[1]!=0) res[1][13]=a53;
  a53=(a05/a13);
  a16=(a16+a16);
  a52=(a16*a08);
  a52=(a53-a52);
  if (res[1]!=0) res[1][14]=a52;
  if (res[1]!=0) res[1][15]=a27;
  if (res[1]!=0) res[1][16]=a33;
  if (res[1]!=0) res[1][17]=a34;
  if (res[1]!=0) res[1][18]=a35;
  if (res[1]!=0) res[1][19]=a37;
  if (res[1]!=0) res[1][20]=a32;
  if (res[2]!=0) res[2][0]=a36;
  if (res[2]!=0) res[2][1]=a36;
  if (res[2]!=0) res[2][2]=a36;
  if (res[2]!=0) res[2][3]=a36;
  if (res[2]!=0) res[2][4]=a36;
  if (res[2]!=0) res[2][5]=a36;
  if (res[2]!=0) res[2][6]=a36;
  if (res[2]!=0) res[2][7]=a36;
  if (res[2]!=0) res[2][8]=a00;
  if (res[2]!=0) res[2][9]=a00;
  if (res[2]!=0) res[2][10]=a07;
  a07=(a06*a17);
  a36=(a19*a07);
  a32=(a28*a17);
  a37=(a11*a32);
  a36=(a36+a37);
  a37=(a03*a17);
  a35=(a21*a37);
  a36=(a36-a35);
  a35=(1./a13);
  a34=(a25*a17);
  a34=(a35-a34);
  a33=(a23*a34);
  a36=(a36+a33);
  a33=(a00*a36);
  a33=(a26*a33);
  a36=(a26*a36);
  a36=(a00*a36);
  a33=(a33+a36);
  a36=(a23*a33);
  a27=(a19*a32);
  a52=(a11*a07);
  a27=(a27-a52);
  a52=(a21*a34);
  a27=(a27+a52);
  a52=(a23*a37);
  a27=(a27+a52);
  a52=(a10*a27);
  a52=(a26*a52);
  a27=(a26*a27);
  a27=(a10*a27);
  a52=(a52+a27);
  a27=(a21*a52);
  a36=(a36+a27);
  a27=(a11*a34);
  a51=(a19*a37);
  a27=(a27+a51);
  a51=(a21*a07);
  a27=(a27+a51);
  a51=(a23*a32);
  a27=(a27-a51);
  a51=(a10*a27);
  a51=(a26*a51);
  a27=(a26*a27);
  a27=(a10*a27);
  a51=(a51+a27);
  a27=(a11*a51);
  a36=(a36+a27);
  a27=(a36/a13);
  a18=(a18/a13);
  a50=(a18*a17);
  a27=(a27-a50);
  a50=(a26*a08);
  a49=(a23*a51);
  a48=(a11*a33);
  a47=(a19*a52);
  a48=(a48+a47);
  a49=(a49-a48);
  a49=(a28*a49);
  a32=(a32/a13);
  a48=(a28/a13);
  a47=(a48*a17);
  a32=(a32+a47);
  a32=(a09*a32);
  a49=(a49-a32);
  a32=(a11*a52);
  a47=(a19*a33);
  a32=(a32-a47);
  a47=(a21*a51);
  a32=(a32-a47);
  a32=(a06*a32);
  a07=(a07/a13);
  a47=(a06/a13);
  a46=(a47*a17);
  a07=(a07+a46);
  a07=(a05*a07);
  a32=(a32-a07);
  a49=(a49+a32);
  a33=(a21*a33);
  a52=(a23*a52);
  a33=(a33-a52);
  a51=(a19*a51);
  a33=(a33-a51);
  a33=(a03*a33);
  a37=(a37/a13);
  a51=(a03/a13);
  a52=(a51*a17);
  a37=(a37+a52);
  a37=(a31*a37);
  a33=(a33-a37);
  a49=(a49+a33);
  a34=(a34/a13);
  a33=(a25/a13);
  a37=(a33*a17);
  a34=(a34-a37);
  a34=(a30*a34);
  a36=(a25*a36);
  a34=(a34+a36);
  a49=(a49+a34);
  a49=(a49/a29);
  a08=(a08/a29);
  a17=(a17+a17);
  a17=(a08*a17);
  a49=(a49-a17);
  a49=(a12*a49);
  a49=(a50+a49);
  a27=(a27-a49);
  if (res[2]!=0) res[2][11]=a27;
  a27=(a03*a20);
  a27=(a35-a27);
  a49=(a21*a27);
  a17=(a06*a20);
  a34=(a19*a17);
  a36=(a28*a20);
  a37=(a11*a36);
  a34=(a34+a37);
  a49=(a49+a34);
  a34=(a25*a20);
  a37=(a23*a34);
  a49=(a49-a37);
  a37=(a00*a49);
  a37=(a26*a37);
  a49=(a26*a49);
  a49=(a00*a49);
  a37=(a37+a49);
  a49=(a23*a37);
  a52=(a19*a36);
  a32=(a11*a17);
  a52=(a52-a32);
  a32=(a21*a34);
  a52=(a52-a32);
  a32=(a23*a27);
  a52=(a52-a32);
  a32=(a10*a52);
  a32=(a26*a32);
  a52=(a26*a52);
  a52=(a10*a52);
  a32=(a32+a52);
  a52=(a21*a32);
  a49=(a49+a52);
  a52=(a21*a17);
  a07=(a11*a34);
  a46=(a19*a27);
  a07=(a07+a46);
  a52=(a52-a07);
  a07=(a23*a36);
  a52=(a52-a07);
  a07=(a10*a52);
  a07=(a26*a07);
  a52=(a26*a52);
  a52=(a10*a52);
  a07=(a07+a52);
  a52=(a11*a07);
  a49=(a49+a52);
  a52=(a49/a13);
  a46=(a18*a20);
  a52=(a52-a46);
  a46=(a23*a07);
  a45=(a11*a37);
  a44=(a19*a32);
  a45=(a45+a44);
  a46=(a46-a45);
  a46=(a28*a46);
  a36=(a36/a13);
  a45=(a48*a20);
  a36=(a36+a45);
  a36=(a09*a36);
  a46=(a46-a36);
  a36=(a11*a32);
  a45=(a19*a37);
  a36=(a36-a45);
  a45=(a21*a07);
  a36=(a36-a45);
  a36=(a06*a36);
  a17=(a17/a13);
  a45=(a47*a20);
  a17=(a17+a45);
  a17=(a05*a17);
  a36=(a36-a17);
  a46=(a46+a36);
  a27=(a27/a13);
  a36=(a51*a20);
  a27=(a27-a36);
  a27=(a31*a27);
  a37=(a21*a37);
  a32=(a23*a32);
  a37=(a37-a32);
  a07=(a19*a07);
  a37=(a37-a07);
  a07=(a03*a37);
  a27=(a27+a07);
  a46=(a46+a27);
  a49=(a25*a49);
  a34=(a34/a13);
  a27=(a33*a20);
  a34=(a34+a27);
  a34=(a30*a34);
  a49=(a49-a34);
  a46=(a46+a49);
  a46=(a46/a29);
  a49=(a20+a20);
  a49=(a08*a49);
  a46=(a46-a49);
  a49=(a12*a46);
  a52=(a52-a49);
  if (res[2]!=0) res[2][12]=a52;
  a49=(a03*a24);
  a34=(a23*a49);
  a27=(a06*a24);
  a07=(a11*a27);
  a32=(a28*a24);
  a32=(a35-a32);
  a36=(a19*a32);
  a07=(a07+a36);
  a36=(a25*a24);
  a17=(a21*a36);
  a07=(a07+a17);
  a34=(a34-a07);
  a07=(a10*a34);
  a07=(a26*a07);
  a34=(a26*a34);
  a34=(a10*a34);
  a07=(a07+a34);
  a34=(a21*a07);
  a17=(a21*a49);
  a45=(a11*a32);
  a44=(a19*a27);
  a45=(a45-a44);
  a17=(a17+a45);
  a45=(a23*a36);
  a17=(a17+a45);
  a45=(a00*a17);
  a45=(a26*a45);
  a17=(a26*a17);
  a17=(a00*a17);
  a45=(a45+a17);
  a17=(a23*a45);
  a34=(a34-a17);
  a17=(a19*a49);
  a44=(a11*a36);
  a17=(a17-a44);
  a44=(a21*a27);
  a17=(a17+a44);
  a44=(a23*a32);
  a17=(a17+a44);
  a44=(a10*a17);
  a44=(a26*a44);
  a17=(a26*a17);
  a17=(a10*a17);
  a44=(a44+a17);
  a17=(a11*a44);
  a34=(a34+a17);
  a17=(a34/a13);
  a43=(a18*a24);
  a17=(a17-a43);
  a32=(a32/a13);
  a43=(a48*a24);
  a32=(a32-a43);
  a32=(a09*a32);
  a43=(a23*a44);
  a42=(a19*a07);
  a41=(a11*a45);
  a42=(a42-a41);
  a43=(a43-a42);
  a42=(a28*a43);
  a32=(a32+a42);
  a42=(a11*a07);
  a41=(a19*a45);
  a42=(a42+a41);
  a41=(a21*a44);
  a42=(a42-a41);
  a42=(a06*a42);
  a27=(a27/a13);
  a41=(a47*a24);
  a27=(a27+a41);
  a27=(a05*a27);
  a42=(a42-a27);
  a32=(a32+a42);
  a49=(a49/a13);
  a42=(a51*a24);
  a49=(a49+a42);
  a49=(a31*a49);
  a45=(a21*a45);
  a07=(a23*a07);
  a45=(a45+a07);
  a44=(a19*a44);
  a45=(a45+a44);
  a44=(a03*a45);
  a49=(a49+a44);
  a32=(a32-a49);
  a34=(a25*a34);
  a36=(a36/a13);
  a49=(a33*a24);
  a36=(a36+a49);
  a36=(a30*a36);
  a34=(a34-a36);
  a32=(a32+a34);
  a32=(a32/a29);
  a34=(a24+a24);
  a34=(a08*a34);
  a32=(a32-a34);
  a34=(a12*a32);
  a17=(a17-a34);
  if (res[2]!=0) res[2][13]=a17;
  a34=(a06*a22);
  a35=(a35-a34);
  a34=(a11*a35);
  a36=(a28*a22);
  a49=(a19*a36);
  a34=(a34+a49);
  a49=(a25*a22);
  a44=(a21*a49);
  a34=(a34-a44);
  a44=(a03*a22);
  a07=(a23*a44);
  a34=(a34+a07);
  a07=(a10*a34);
  a07=(a26*a07);
  a34=(a26*a34);
  a34=(a10*a34);
  a07=(a07+a34);
  a34=(a21*a07);
  a42=(a21*a44);
  a27=(a19*a35);
  a41=(a11*a36);
  a27=(a27-a41);
  a42=(a42+a27);
  a27=(a23*a49);
  a42=(a42+a27);
  a27=(a00*a42);
  a27=(a26*a27);
  a42=(a26*a42);
  a00=(a00*a42);
  a27=(a27+a00);
  a00=(a23*a27);
  a34=(a34-a00);
  a00=(a19*a44);
  a42=(a11*a49);
  a00=(a00-a42);
  a42=(a21*a35);
  a00=(a00-a42);
  a42=(a23*a36);
  a00=(a00-a42);
  a42=(a10*a00);
  a42=(a26*a42);
  a26=(a26*a00);
  a10=(a10*a26);
  a42=(a42+a10);
  a10=(a11*a42);
  a34=(a34+a10);
  a10=(a34/a13);
  a18=(a18*a22);
  a10=(a10-a18);
  a18=(a23*a42);
  a26=(a19*a07);
  a00=(a11*a27);
  a26=(a26-a00);
  a18=(a18-a26);
  a28=(a28*a18);
  a36=(a36/a13);
  a48=(a48*a22);
  a36=(a36+a48);
  a09=(a09*a36);
  a28=(a28-a09);
  a35=(a35/a13);
  a47=(a47*a22);
  a35=(a35-a47);
  a05=(a05*a35);
  a11=(a11*a07);
  a35=(a19*a27);
  a11=(a11+a35);
  a35=(a21*a42);
  a11=(a11-a35);
  a06=(a06*a11);
  a05=(a05+a06);
  a28=(a28+a05);
  a44=(a44/a13);
  a51=(a51*a22);
  a44=(a44+a51);
  a31=(a31*a44);
  a21=(a21*a27);
  a23=(a23*a07);
  a21=(a21+a23);
  a19=(a19*a42);
  a21=(a21+a19);
  a03=(a03*a21);
  a31=(a31+a03);
  a28=(a28-a31);
  a25=(a25*a34);
  a49=(a49/a13);
  a33=(a33*a22);
  a49=(a49+a33);
  a30=(a30*a49);
  a25=(a25-a30);
  a28=(a28+a25);
  a28=(a28/a29);
  a29=(a22+a22);
  a08=(a08*a29);
  a28=(a28-a08);
  a12=(a12*a28);
  a10=(a10-a12);
  if (res[2]!=0) res[2][14]=a10;
  if (res[2]!=0) res[2][15]=a52;
  a37=(a37/a13);
  a02=(a02/a13);
  a20=(a02*a20);
  a37=(a37-a20);
  a46=(a14*a46);
  a46=(a50+a46);
  a37=(a37-a46);
  if (res[2]!=0) res[2][16]=a37;
  a45=(a45/a13);
  a37=(a02*a24);
  a45=(a45+a37);
  a37=(a14*a32);
  a45=(a45+a37);
  a45=(-a45);
  if (res[2]!=0) res[2][17]=a45;
  a21=(a21/a13);
  a02=(a02*a22);
  a21=(a21+a02);
  a14=(a14*a28);
  a21=(a21+a14);
  a21=(-a21);
  if (res[2]!=0) res[2][18]=a21;
  if (res[2]!=0) res[2][19]=a17;
  if (res[2]!=0) res[2][20]=a45;
  a43=(a43/a13);
  a54=(a54/a13);
  a24=(a54*a24);
  a43=(a43-a24);
  a32=(a15*a32);
  a32=(a50+a32);
  a43=(a43-a32);
  if (res[2]!=0) res[2][21]=a43;
  a18=(a18/a13);
  a54=(a54*a22);
  a18=(a18-a54);
  a15=(a15*a28);
  a18=(a18-a15);
  if (res[2]!=0) res[2][22]=a18;
  if (res[2]!=0) res[2][23]=a10;
  if (res[2]!=0) res[2][24]=a21;
  if (res[2]!=0) res[2][25]=a18;
  a11=(a11/a13);
  a53=(a53/a13);
  a53=(a53*a22);
  a11=(a11-a53);
  a16=(a16*a28);
  a50=(a50+a16);
  a11=(a11-a50);
  if (res[2]!=0) res[2][26]=a11;
  a11=1.;
  if (res[2]!=0) res[2][27]=a11;
  if (res[2]!=0) res[2][28]=a11;
  if (res[2]!=0) res[2][29]=a11;
  if (res[2]!=0) res[2][30]=a01;
  if (res[2]!=0) res[2][31]=a01;
  if (res[2]!=0) res[2][32]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_0_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
