/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[41] = 
  {13, 13, 0, 1, 2, 3, 7, 11,
  15, 19, 20, 21, 22, 23, 24, 25,
  0, 1, 2, 3, 4, 5, 6, 3,
  4, 5, 6, 3, 4, 5, 6, 3,
  4, 5, 6, 7, 8, 9, 10, 11,
  12};

/* BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess:(i0[13],i1[13])->(o0,o1[13],o2[13x13,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49;
  a00=1200.;
  a01=5.0000000000000000e-01;
  a02=arg[0]? arg[0][0] : 0;
  a03=arg[1]? arg[1][0] : 0;
  a02=(a02-a03);
  a03=(a01*a02);
  a03=(a00*a03);
  a04=(a03*a02);
  a05=arg[0]? arg[0][1] : 0;
  a06=arg[1]? arg[1][1] : 0;
  a05=(a05-a06);
  a06=(a01*a05);
  a06=(a00*a06);
  a07=(a06*a05);
  a04=(a04+a07);
  a07=1500.;
  a08=arg[0]? arg[0][2] : 0;
  a09=arg[1]? arg[1][2] : 0;
  a08=(a08-a09);
  a09=(a01*a08);
  a09=(a07*a09);
  a10=(a09*a08);
  a04=(a04+a10);
  a10=1000.;
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[0]? arg[0][3] : 0;
  a13=casadi_sq(a12);
  a14=arg[0]? arg[0][4] : 0;
  a15=casadi_sq(a14);
  a13=(a13+a15);
  a15=arg[0]? arg[0][5] : 0;
  a16=casadi_sq(a15);
  a13=(a13+a16);
  a16=arg[0]? arg[0][6] : 0;
  a17=casadi_sq(a16);
  a13=(a13+a17);
  a13=sqrt(a13);
  a17=(a12/a13);
  a18=(a11*a17);
  a19=arg[1]? arg[1][3] : 0;
  a20=(a14/a13);
  a21=(a19*a20);
  a18=(a18-a21);
  a21=arg[1]? arg[1][5] : 0;
  a22=(a16/a13);
  a23=(a21*a22);
  a18=(a18-a23);
  a23=arg[1]? arg[1][6] : 0;
  a24=(a15/a13);
  a25=(a23*a24);
  a18=(a18+a25);
  a25=(a10*a18);
  a26=2.;
  a18=(a26*a18);
  a27=(a25*a18);
  a28=(a11*a22);
  a29=(a19*a24);
  a28=(a28-a29);
  a29=(a21*a17);
  a28=(a28+a29);
  a29=(a23*a20);
  a28=(a28-a29);
  a29=(a10*a28);
  a28=(a26*a28);
  a30=(a29*a28);
  a27=(a27+a30);
  a30=(a21*a20);
  a31=(a19*a22);
  a32=(a11*a24);
  a31=(a31+a32);
  a30=(a30-a31);
  a31=(a23*a17);
  a30=(a30+a31);
  a31=(a00*a30);
  a30=(a26*a30);
  a32=(a31*a30);
  a27=(a27+a32);
  a04=(a04+a27);
  a27=10.;
  a32=arg[0]? arg[0][7] : 0;
  a33=arg[1]? arg[1][7] : 0;
  a32=(a32-a33);
  a33=(a01*a32);
  a33=(a27*a33);
  a34=(a33*a32);
  a35=arg[0]? arg[0][8] : 0;
  a36=arg[1]? arg[1][8] : 0;
  a35=(a35-a36);
  a36=(a01*a35);
  a36=(a27*a36);
  a37=(a36*a35);
  a34=(a34+a37);
  a37=arg[0]? arg[0][9] : 0;
  a38=arg[1]? arg[1][9] : 0;
  a37=(a37-a38);
  a38=(a01*a37);
  a38=(a27*a38);
  a39=(a38*a37);
  a34=(a34+a39);
  a04=(a04+a34);
  a34=5.;
  a39=arg[0]? arg[0][10] : 0;
  a40=arg[1]? arg[1][10] : 0;
  a39=(a39-a40);
  a40=(a01*a39);
  a40=(a34*a40);
  a41=(a40*a39);
  a42=arg[0]? arg[0][11] : 0;
  a43=arg[1]? arg[1][11] : 0;
  a42=(a42-a43);
  a43=(a01*a42);
  a43=(a34*a43);
  a44=(a43*a42);
  a41=(a41+a44);
  a44=arg[0]? arg[0][12] : 0;
  a45=arg[1]? arg[1][12] : 0;
  a44=(a44-a45);
  a45=(a01*a44);
  a45=(a34*a45);
  a46=(a45*a44);
  a41=(a41+a46);
  a04=(a04+a41);
  if (res[0]!=0) res[0][0]=a04;
  a02=(a00*a02);
  a02=(a01*a02);
  a03=(a03+a02);
  if (res[1]!=0) res[1][0]=a03;
  a05=(a00*a05);
  a05=(a01*a05);
  a06=(a06+a05);
  if (res[1]!=0) res[1][1]=a06;
  a08=(a07*a08);
  a08=(a01*a08);
  a09=(a09+a08);
  if (res[1]!=0) res[1][2]=a09;
  a31=(a26*a31);
  a30=(a00*a30);
  a31=(a31+a30);
  a30=(a23*a31);
  a29=(a26*a29);
  a28=(a10*a28);
  a29=(a29+a28);
  a28=(a21*a29);
  a30=(a30+a28);
  a25=(a26*a25);
  a18=(a10*a18);
  a25=(a25+a18);
  a18=(a11*a25);
  a30=(a30+a18);
  a18=(a30/a13);
  a12=(a12+a12);
  a28=(a24/a13);
  a09=(a23*a25);
  a08=(a11*a31);
  a06=(a19*a29);
  a08=(a08+a06);
  a09=(a09-a08);
  a08=(a28*a09);
  a06=(a22/a13);
  a05=(a11*a29);
  a03=(a19*a31);
  a05=(a05-a03);
  a03=(a21*a25);
  a05=(a05-a03);
  a03=(a06*a05);
  a08=(a08+a03);
  a03=(a20/a13);
  a31=(a21*a31);
  a29=(a23*a29);
  a31=(a31-a29);
  a25=(a19*a25);
  a31=(a31-a25);
  a25=(a03*a31);
  a08=(a08+a25);
  a25=(a17/a13);
  a29=(a25*a30);
  a08=(a08+a29);
  a29=(a13+a13);
  a08=(a08/a29);
  a02=(a12*a08);
  a02=(a18-a02);
  if (res[1]!=0) res[1][3]=a02;
  a02=(a31/a13);
  a14=(a14+a14);
  a04=(a14*a08);
  a04=(a02-a04);
  if (res[1]!=0) res[1][4]=a04;
  a04=(a09/a13);
  a15=(a15+a15);
  a41=(a15*a08);
  a41=(a04-a41);
  if (res[1]!=0) res[1][5]=a41;
  a41=(a05/a13);
  a16=(a16+a16);
  a46=(a16*a08);
  a46=(a41-a46);
  if (res[1]!=0) res[1][6]=a46;
  a32=(a27*a32);
  a32=(a01*a32);
  a33=(a33+a32);
  if (res[1]!=0) res[1][7]=a33;
  a35=(a27*a35);
  a35=(a01*a35);
  a36=(a36+a35);
  if (res[1]!=0) res[1][8]=a36;
  a37=(a27*a37);
  a37=(a01*a37);
  a38=(a38+a37);
  if (res[1]!=0) res[1][9]=a38;
  a39=(a34*a39);
  a39=(a01*a39);
  a40=(a40+a39);
  if (res[1]!=0) res[1][10]=a40;
  a42=(a34*a42);
  a42=(a01*a42);
  a43=(a43+a42);
  if (res[1]!=0) res[1][11]=a43;
  a44=(a34*a44);
  a01=(a01*a44);
  a45=(a45+a01);
  if (res[1]!=0) res[1][12]=a45;
  if (res[2]!=0) res[2][0]=a00;
  if (res[2]!=0) res[2][1]=a00;
  if (res[2]!=0) res[2][2]=a07;
  a07=(a06*a17);
  a45=(a19*a07);
  a01=(a28*a17);
  a44=(a11*a01);
  a45=(a45+a44);
  a44=(a03*a17);
  a43=(a21*a44);
  a45=(a45-a43);
  a43=(1./a13);
  a42=(a25*a17);
  a42=(a43-a42);
  a40=(a23*a42);
  a45=(a45+a40);
  a40=(a00*a45);
  a40=(a26*a40);
  a45=(a26*a45);
  a45=(a00*a45);
  a40=(a40+a45);
  a45=(a23*a40);
  a39=(a19*a01);
  a38=(a11*a07);
  a39=(a39-a38);
  a38=(a21*a42);
  a39=(a39+a38);
  a38=(a23*a44);
  a39=(a39+a38);
  a38=(a10*a39);
  a38=(a26*a38);
  a39=(a26*a39);
  a39=(a10*a39);
  a38=(a38+a39);
  a39=(a21*a38);
  a45=(a45+a39);
  a39=(a11*a42);
  a37=(a19*a44);
  a39=(a39+a37);
  a37=(a21*a07);
  a39=(a39+a37);
  a37=(a23*a01);
  a39=(a39-a37);
  a37=(a10*a39);
  a37=(a26*a37);
  a39=(a26*a39);
  a39=(a10*a39);
  a37=(a37+a39);
  a39=(a11*a37);
  a45=(a45+a39);
  a39=(a45/a13);
  a18=(a18/a13);
  a36=(a18*a17);
  a39=(a39-a36);
  a36=(a26*a08);
  a35=(a23*a37);
  a33=(a11*a40);
  a32=(a19*a38);
  a33=(a33+a32);
  a35=(a35-a33);
  a33=(a28*a35);
  a01=(a01/a13);
  a32=(a28/a13);
  a46=(a32*a17);
  a01=(a01+a46);
  a01=(a09*a01);
  a33=(a33-a01);
  a01=(a11*a38);
  a46=(a19*a40);
  a01=(a01-a46);
  a46=(a21*a37);
  a01=(a01-a46);
  a46=(a06*a01);
  a07=(a07/a13);
  a47=(a06/a13);
  a48=(a47*a17);
  a07=(a07+a48);
  a07=(a05*a07);
  a46=(a46-a07);
  a33=(a33+a46);
  a40=(a21*a40);
  a38=(a23*a38);
  a40=(a40-a38);
  a37=(a19*a37);
  a40=(a40-a37);
  a37=(a03*a40);
  a44=(a44/a13);
  a38=(a03/a13);
  a46=(a38*a17);
  a44=(a44+a46);
  a44=(a31*a44);
  a37=(a37-a44);
  a33=(a33+a37);
  a42=(a42/a13);
  a37=(a25/a13);
  a44=(a37*a17);
  a42=(a42-a44);
  a42=(a30*a42);
  a45=(a25*a45);
  a42=(a42+a45);
  a33=(a33+a42);
  a33=(a33/a29);
  a08=(a08/a29);
  a42=(a17+a17);
  a42=(a08*a42);
  a33=(a33-a42);
  a42=(a12*a33);
  a42=(a36+a42);
  a39=(a39-a42);
  if (res[2]!=0) res[2][3]=a39;
  a40=(a40/a13);
  a02=(a02/a13);
  a39=(a02*a17);
  a40=(a40-a39);
  a39=(a14*a33);
  a40=(a40-a39);
  if (res[2]!=0) res[2][4]=a40;
  a35=(a35/a13);
  a04=(a04/a13);
  a40=(a04*a17);
  a35=(a35-a40);
  a40=(a15*a33);
  a35=(a35-a40);
  if (res[2]!=0) res[2][5]=a35;
  a01=(a01/a13);
  a41=(a41/a13);
  a17=(a41*a17);
  a01=(a01-a17);
  a33=(a16*a33);
  a01=(a01-a33);
  if (res[2]!=0) res[2][6]=a01;
  a01=(a03*a20);
  a01=(a43-a01);
  a33=(a21*a01);
  a17=(a06*a20);
  a35=(a19*a17);
  a40=(a28*a20);
  a39=(a11*a40);
  a35=(a35+a39);
  a33=(a33+a35);
  a35=(a25*a20);
  a39=(a23*a35);
  a33=(a33-a39);
  a39=(a00*a33);
  a39=(a26*a39);
  a33=(a26*a33);
  a33=(a00*a33);
  a39=(a39+a33);
  a33=(a23*a39);
  a42=(a19*a40);
  a45=(a11*a17);
  a42=(a42-a45);
  a45=(a21*a35);
  a42=(a42-a45);
  a45=(a23*a01);
  a42=(a42-a45);
  a45=(a10*a42);
  a45=(a26*a45);
  a42=(a26*a42);
  a42=(a10*a42);
  a45=(a45+a42);
  a42=(a21*a45);
  a33=(a33+a42);
  a42=(a21*a17);
  a44=(a11*a35);
  a46=(a19*a01);
  a44=(a44+a46);
  a42=(a42-a44);
  a44=(a23*a40);
  a42=(a42-a44);
  a44=(a10*a42);
  a44=(a26*a44);
  a42=(a26*a42);
  a42=(a10*a42);
  a44=(a44+a42);
  a42=(a11*a44);
  a33=(a33+a42);
  a42=(a33/a13);
  a46=(a18*a20);
  a42=(a42-a46);
  a46=(a23*a44);
  a07=(a11*a39);
  a48=(a19*a45);
  a07=(a07+a48);
  a46=(a46-a07);
  a07=(a28*a46);
  a40=(a40/a13);
  a48=(a32*a20);
  a40=(a40+a48);
  a40=(a09*a40);
  a07=(a07-a40);
  a40=(a11*a45);
  a48=(a19*a39);
  a40=(a40-a48);
  a48=(a21*a44);
  a40=(a40-a48);
  a48=(a06*a40);
  a17=(a17/a13);
  a49=(a47*a20);
  a17=(a17+a49);
  a17=(a05*a17);
  a48=(a48-a17);
  a07=(a07+a48);
  a01=(a01/a13);
  a48=(a38*a20);
  a01=(a01-a48);
  a01=(a31*a01);
  a39=(a21*a39);
  a45=(a23*a45);
  a39=(a39-a45);
  a44=(a19*a44);
  a39=(a39-a44);
  a44=(a03*a39);
  a01=(a01+a44);
  a07=(a07+a01);
  a33=(a25*a33);
  a35=(a35/a13);
  a01=(a37*a20);
  a35=(a35+a01);
  a35=(a30*a35);
  a33=(a33-a35);
  a07=(a07+a33);
  a07=(a07/a29);
  a33=(a20+a20);
  a33=(a08*a33);
  a07=(a07-a33);
  a33=(a12*a07);
  a42=(a42-a33);
  if (res[2]!=0) res[2][7]=a42;
  a39=(a39/a13);
  a42=(a02*a20);
  a39=(a39-a42);
  a42=(a14*a07);
  a42=(a36+a42);
  a39=(a39-a42);
  if (res[2]!=0) res[2][8]=a39;
  a46=(a46/a13);
  a39=(a04*a20);
  a46=(a46-a39);
  a39=(a15*a07);
  a46=(a46-a39);
  if (res[2]!=0) res[2][9]=a46;
  a40=(a40/a13);
  a20=(a41*a20);
  a40=(a40-a20);
  a07=(a16*a07);
  a40=(a40-a07);
  if (res[2]!=0) res[2][10]=a40;
  a40=(a03*a24);
  a07=(a23*a40);
  a20=(a06*a24);
  a46=(a11*a20);
  a39=(a28*a24);
  a39=(a43-a39);
  a42=(a19*a39);
  a46=(a46+a42);
  a42=(a25*a24);
  a33=(a21*a42);
  a46=(a46+a33);
  a07=(a07-a46);
  a46=(a10*a07);
  a46=(a26*a46);
  a07=(a26*a07);
  a07=(a10*a07);
  a46=(a46+a07);
  a07=(a21*a46);
  a33=(a21*a40);
  a35=(a11*a39);
  a01=(a19*a20);
  a35=(a35-a01);
  a33=(a33+a35);
  a35=(a23*a42);
  a33=(a33+a35);
  a35=(a00*a33);
  a35=(a26*a35);
  a33=(a26*a33);
  a33=(a00*a33);
  a35=(a35+a33);
  a33=(a23*a35);
  a07=(a07-a33);
  a33=(a19*a40);
  a01=(a11*a42);
  a33=(a33-a01);
  a01=(a21*a20);
  a33=(a33+a01);
  a01=(a23*a39);
  a33=(a33+a01);
  a01=(a10*a33);
  a01=(a26*a01);
  a33=(a26*a33);
  a33=(a10*a33);
  a01=(a01+a33);
  a33=(a11*a01);
  a07=(a07+a33);
  a33=(a07/a13);
  a44=(a18*a24);
  a33=(a33-a44);
  a39=(a39/a13);
  a44=(a32*a24);
  a39=(a39-a44);
  a39=(a09*a39);
  a44=(a23*a01);
  a45=(a19*a46);
  a48=(a11*a35);
  a45=(a45-a48);
  a44=(a44-a45);
  a45=(a28*a44);
  a39=(a39+a45);
  a45=(a11*a46);
  a48=(a19*a35);
  a45=(a45+a48);
  a48=(a21*a01);
  a45=(a45-a48);
  a48=(a06*a45);
  a20=(a20/a13);
  a17=(a47*a24);
  a20=(a20+a17);
  a20=(a05*a20);
  a48=(a48-a20);
  a39=(a39+a48);
  a40=(a40/a13);
  a48=(a38*a24);
  a40=(a40+a48);
  a40=(a31*a40);
  a35=(a21*a35);
  a46=(a23*a46);
  a35=(a35+a46);
  a01=(a19*a01);
  a35=(a35+a01);
  a01=(a03*a35);
  a40=(a40+a01);
  a39=(a39-a40);
  a07=(a25*a07);
  a42=(a42/a13);
  a40=(a37*a24);
  a42=(a42+a40);
  a42=(a30*a42);
  a07=(a07-a42);
  a39=(a39+a07);
  a39=(a39/a29);
  a07=(a24+a24);
  a07=(a08*a07);
  a39=(a39-a07);
  a07=(a12*a39);
  a33=(a33-a07);
  if (res[2]!=0) res[2][11]=a33;
  a35=(a35/a13);
  a33=(a02*a24);
  a35=(a35+a33);
  a33=(a14*a39);
  a35=(a35+a33);
  a35=(-a35);
  if (res[2]!=0) res[2][12]=a35;
  a44=(a44/a13);
  a35=(a04*a24);
  a44=(a44-a35);
  a35=(a15*a39);
  a35=(a36+a35);
  a44=(a44-a35);
  if (res[2]!=0) res[2][13]=a44;
  a45=(a45/a13);
  a24=(a41*a24);
  a45=(a45-a24);
  a39=(a16*a39);
  a45=(a45-a39);
  if (res[2]!=0) res[2][14]=a45;
  a45=(a06*a22);
  a43=(a43-a45);
  a45=(a11*a43);
  a39=(a28*a22);
  a24=(a19*a39);
  a45=(a45+a24);
  a24=(a25*a22);
  a44=(a21*a24);
  a45=(a45-a44);
  a44=(a03*a22);
  a35=(a23*a44);
  a45=(a45+a35);
  a35=(a10*a45);
  a35=(a26*a35);
  a45=(a26*a45);
  a45=(a10*a45);
  a35=(a35+a45);
  a45=(a21*a35);
  a33=(a21*a44);
  a07=(a19*a43);
  a42=(a11*a39);
  a07=(a07-a42);
  a33=(a33+a07);
  a07=(a23*a24);
  a33=(a33+a07);
  a07=(a00*a33);
  a07=(a26*a07);
  a33=(a26*a33);
  a00=(a00*a33);
  a07=(a07+a00);
  a00=(a23*a07);
  a45=(a45-a00);
  a00=(a19*a44);
  a33=(a11*a24);
  a00=(a00-a33);
  a33=(a21*a43);
  a00=(a00-a33);
  a33=(a23*a39);
  a00=(a00-a33);
  a33=(a10*a00);
  a33=(a26*a33);
  a26=(a26*a00);
  a10=(a10*a26);
  a33=(a33+a10);
  a10=(a11*a33);
  a45=(a45+a10);
  a10=(a45/a13);
  a18=(a18*a22);
  a10=(a10-a18);
  a18=(a23*a33);
  a26=(a19*a35);
  a00=(a11*a07);
  a26=(a26-a00);
  a18=(a18-a26);
  a28=(a28*a18);
  a39=(a39/a13);
  a32=(a32*a22);
  a39=(a39+a32);
  a09=(a09*a39);
  a28=(a28-a09);
  a43=(a43/a13);
  a47=(a47*a22);
  a43=(a43-a47);
  a05=(a05*a43);
  a11=(a11*a35);
  a43=(a19*a07);
  a11=(a11+a43);
  a43=(a21*a33);
  a11=(a11-a43);
  a06=(a06*a11);
  a05=(a05+a06);
  a28=(a28+a05);
  a44=(a44/a13);
  a38=(a38*a22);
  a44=(a44+a38);
  a31=(a31*a44);
  a21=(a21*a07);
  a23=(a23*a35);
  a21=(a21+a23);
  a19=(a19*a33);
  a21=(a21+a19);
  a03=(a03*a21);
  a31=(a31+a03);
  a28=(a28-a31);
  a25=(a25*a45);
  a24=(a24/a13);
  a37=(a37*a22);
  a24=(a24+a37);
  a30=(a30*a24);
  a25=(a25-a30);
  a28=(a28+a25);
  a28=(a28/a29);
  a29=(a22+a22);
  a08=(a08*a29);
  a28=(a28-a08);
  a12=(a12*a28);
  a10=(a10-a12);
  if (res[2]!=0) res[2][15]=a10;
  a21=(a21/a13);
  a02=(a02*a22);
  a21=(a21+a02);
  a14=(a14*a28);
  a21=(a21+a14);
  a21=(-a21);
  if (res[2]!=0) res[2][16]=a21;
  a18=(a18/a13);
  a04=(a04*a22);
  a18=(a18-a04);
  a15=(a15*a28);
  a18=(a18-a15);
  if (res[2]!=0) res[2][17]=a18;
  a11=(a11/a13);
  a41=(a41*a22);
  a11=(a11-a41);
  a16=(a16*a28);
  a36=(a36+a16);
  a11=(a11-a36);
  if (res[2]!=0) res[2][18]=a11;
  if (res[2]!=0) res[2][19]=a27;
  if (res[2]!=0) res[2][20]=a27;
  if (res[2]!=0) res[2][21]=a27;
  if (res[2]!=0) res[2][22]=a34;
  if (res[2]!=0) res[2][23]=a34;
  if (res[2]!=0) res[2][24]=a34;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
