/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};

/* BlueROV_Heavy_cost_ext_cost_e_fun_jac:(i0[13],i1[13])->(o0,o1[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46;
  a00=1200.;
  a01=5.0000000000000000e-01;
  a02=arg[0]? arg[0][0] : 0;
  a03=arg[1]? arg[1][0] : 0;
  a02=(a02-a03);
  a03=(a01*a02);
  a03=(a00*a03);
  a04=(a03*a02);
  a05=arg[0]? arg[0][1] : 0;
  a06=arg[1]? arg[1][1] : 0;
  a05=(a05-a06);
  a06=(a01*a05);
  a06=(a00*a06);
  a07=(a06*a05);
  a04=(a04+a07);
  a07=1500.;
  a08=arg[0]? arg[0][2] : 0;
  a09=arg[1]? arg[1][2] : 0;
  a08=(a08-a09);
  a09=(a01*a08);
  a09=(a07*a09);
  a10=(a09*a08);
  a04=(a04+a10);
  a10=1000.;
  a11=arg[1]? arg[1][4] : 0;
  a12=arg[0]? arg[0][3] : 0;
  a13=casadi_sq(a12);
  a14=arg[0]? arg[0][4] : 0;
  a15=casadi_sq(a14);
  a13=(a13+a15);
  a15=arg[0]? arg[0][5] : 0;
  a16=casadi_sq(a15);
  a13=(a13+a16);
  a16=arg[0]? arg[0][6] : 0;
  a17=casadi_sq(a16);
  a13=(a13+a17);
  a13=sqrt(a13);
  a17=(a12/a13);
  a18=(a11*a17);
  a19=arg[1]? arg[1][3] : 0;
  a20=(a14/a13);
  a21=(a19*a20);
  a18=(a18-a21);
  a21=arg[1]? arg[1][5] : 0;
  a22=(a16/a13);
  a23=(a21*a22);
  a18=(a18-a23);
  a23=arg[1]? arg[1][6] : 0;
  a24=(a15/a13);
  a25=(a23*a24);
  a18=(a18+a25);
  a25=(a10*a18);
  a26=2.;
  a18=(a26*a18);
  a27=(a25*a18);
  a28=(a11*a22);
  a29=(a19*a24);
  a28=(a28-a29);
  a29=(a21*a17);
  a28=(a28+a29);
  a29=(a23*a20);
  a28=(a28-a29);
  a29=(a10*a28);
  a28=(a26*a28);
  a30=(a29*a28);
  a27=(a27+a30);
  a30=(a21*a20);
  a31=(a19*a22);
  a32=(a11*a24);
  a31=(a31+a32);
  a30=(a30-a31);
  a31=(a23*a17);
  a30=(a30+a31);
  a31=(a00*a30);
  a30=(a26*a30);
  a32=(a31*a30);
  a27=(a27+a32);
  a04=(a04+a27);
  a27=10.;
  a32=arg[0]? arg[0][7] : 0;
  a33=arg[1]? arg[1][7] : 0;
  a32=(a32-a33);
  a33=(a01*a32);
  a33=(a27*a33);
  a34=(a33*a32);
  a35=arg[0]? arg[0][8] : 0;
  a36=arg[1]? arg[1][8] : 0;
  a35=(a35-a36);
  a36=(a01*a35);
  a36=(a27*a36);
  a37=(a36*a35);
  a34=(a34+a37);
  a37=arg[0]? arg[0][9] : 0;
  a38=arg[1]? arg[1][9] : 0;
  a37=(a37-a38);
  a38=(a01*a37);
  a38=(a27*a38);
  a39=(a38*a37);
  a34=(a34+a39);
  a04=(a04+a34);
  a34=5.;
  a39=arg[0]? arg[0][10] : 0;
  a40=arg[1]? arg[1][10] : 0;
  a39=(a39-a40);
  a40=(a01*a39);
  a40=(a34*a40);
  a41=(a40*a39);
  a42=arg[0]? arg[0][11] : 0;
  a43=arg[1]? arg[1][11] : 0;
  a42=(a42-a43);
  a43=(a01*a42);
  a43=(a34*a43);
  a44=(a43*a42);
  a41=(a41+a44);
  a44=arg[0]? arg[0][12] : 0;
  a45=arg[1]? arg[1][12] : 0;
  a44=(a44-a45);
  a45=(a01*a44);
  a45=(a34*a45);
  a46=(a45*a44);
  a41=(a41+a46);
  a04=(a04+a41);
  if (res[0]!=0) res[0][0]=a04;
  a02=(a00*a02);
  a02=(a01*a02);
  a03=(a03+a02);
  if (res[1]!=0) res[1][0]=a03;
  a05=(a00*a05);
  a05=(a01*a05);
  a06=(a06+a05);
  if (res[1]!=0) res[1][1]=a06;
  a07=(a07*a08);
  a07=(a01*a07);
  a09=(a09+a07);
  if (res[1]!=0) res[1][2]=a09;
  a31=(a26*a31);
  a00=(a00*a30);
  a31=(a31+a00);
  a00=(a23*a31);
  a29=(a26*a29);
  a28=(a10*a28);
  a29=(a29+a28);
  a28=(a21*a29);
  a00=(a00+a28);
  a26=(a26*a25);
  a10=(a10*a18);
  a26=(a26+a10);
  a10=(a11*a26);
  a00=(a00+a10);
  a10=(a00/a13);
  a12=(a12+a12);
  a24=(a24/a13);
  a18=(a23*a26);
  a25=(a11*a31);
  a28=(a19*a29);
  a25=(a25+a28);
  a18=(a18-a25);
  a24=(a24*a18);
  a22=(a22/a13);
  a11=(a11*a29);
  a25=(a19*a31);
  a11=(a11-a25);
  a25=(a21*a26);
  a11=(a11-a25);
  a22=(a22*a11);
  a24=(a24+a22);
  a20=(a20/a13);
  a21=(a21*a31);
  a23=(a23*a29);
  a21=(a21-a23);
  a19=(a19*a26);
  a21=(a21-a19);
  a20=(a20*a21);
  a24=(a24+a20);
  a17=(a17/a13);
  a17=(a17*a00);
  a24=(a24+a17);
  a17=(a13+a13);
  a24=(a24/a17);
  a12=(a12*a24);
  a10=(a10-a12);
  if (res[1]!=0) res[1][3]=a10;
  a21=(a21/a13);
  a14=(a14+a14);
  a14=(a14*a24);
  a21=(a21-a14);
  if (res[1]!=0) res[1][4]=a21;
  a18=(a18/a13);
  a15=(a15+a15);
  a15=(a15*a24);
  a18=(a18-a15);
  if (res[1]!=0) res[1][5]=a18;
  a11=(a11/a13);
  a16=(a16+a16);
  a16=(a16*a24);
  a11=(a11-a16);
  if (res[1]!=0) res[1][6]=a11;
  a32=(a27*a32);
  a32=(a01*a32);
  a33=(a33+a32);
  if (res[1]!=0) res[1][7]=a33;
  a35=(a27*a35);
  a35=(a01*a35);
  a36=(a36+a35);
  if (res[1]!=0) res[1][8]=a36;
  a27=(a27*a37);
  a27=(a01*a27);
  a38=(a38+a27);
  if (res[1]!=0) res[1][9]=a38;
  a39=(a34*a39);
  a39=(a01*a39);
  a40=(a40+a39);
  if (res[1]!=0) res[1][10]=a40;
  a42=(a34*a42);
  a42=(a01*a42);
  a43=(a43+a42);
  if (res[1]!=0) res[1][11]=a43;
  a34=(a34*a44);
  a01=(a01*a34);
  a45=(a45+a01);
  if (res[1]!=0) res[1][12]=a45;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_cost_ext_cost_e_fun_jac_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_cost_ext_cost_e_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_cost_ext_cost_e_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_cost_ext_cost_e_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_cost_ext_cost_e_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
