/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[12] = 
  {13, 2, 0, 3, 7, 0, 1, 2,
  3, 4, 5, 6};
static const casadi_int casadi_s3[41] = 
  {13, 13, 0, 3, 6, 9, 13, 17,
  21, 25, 25, 25, 25, 25, 25, 25,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 3, 4, 5, 6, 3, 4, 5,
  6, 3, 4, 5, 6, 3, 4, 5,
  6};

/* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess:(i0[13],i1[2],i2[13])->(o0[2],o1[13x2,7nz],o2[13x13,25nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31;
  a00=0.;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[2]? arg[2][0] : 0;
  a01=(a01-a02);
  a02=casadi_fabs(a01);
  a03=casadi_fmax(a00,a02);
  a04=arg[0]? arg[0][1] : 0;
  a05=arg[2]? arg[2][1] : 0;
  a04=(a04-a05);
  a05=casadi_fabs(a04);
  a06=casadi_fmax(a03,a05);
  a07=arg[0]? arg[0][2] : 0;
  a08=arg[2]? arg[2][2] : 0;
  a07=(a07-a08);
  a08=casadi_fabs(a07);
  a09=casadi_fmax(a06,a08);
  if (res[0]!=0) res[0][0]=a09;
  a09=arg[2]? arg[2][4] : 0;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a12=arg[0]? arg[0][4] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][5] : 0;
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a14=arg[0]? arg[0][6] : 0;
  a15=casadi_sq(a14);
  a11=(a11+a15);
  a11=sqrt(a11);
  a15=(a10/a11);
  a16=(a09*a15);
  a17=arg[2]? arg[2][3] : 0;
  a18=(a12/a11);
  a19=(a17*a18);
  a16=(a16-a19);
  a19=arg[2]? arg[2][5] : 0;
  a20=(a14/a11);
  a21=(a19*a20);
  a16=(a16-a21);
  a21=arg[2]? arg[2][6] : 0;
  a22=(a13/a11);
  a23=(a21*a22);
  a16=(a16+a23);
  a23=casadi_fabs(a16);
  a24=casadi_fmax(a00,a23);
  a25=(a09*a20);
  a26=(a17*a22);
  a25=(a25-a26);
  a26=(a19*a15);
  a25=(a25+a26);
  a26=(a21*a18);
  a25=(a25-a26);
  a26=casadi_fabs(a25);
  a27=casadi_fmax(a24,a26);
  if (res[0]!=0) res[0][1]=a27;
  a01=casadi_sign(a01);
  a27=(a05<=a03);
  a03=(a03<=a05);
  a05=(a27+a03);
  a27=(a27/a05);
  a28=(a08<=a06);
  a06=(a06<=a08);
  a08=(a28+a06);
  a28=(a28/a08);
  a27=(a27*a28);
  a02=(a02<=a00);
  a29=1.;
  a02=(a02+a29);
  a27=(a27/a02);
  a01=(a01*a27);
  if (res[1]!=0) res[1][0]=a01;
  a04=casadi_sign(a04);
  a03=(a03/a05);
  a03=(a03*a28);
  a04=(a04*a03);
  if (res[1]!=0) res[1][1]=a04;
  a07=casadi_sign(a07);
  a06=(a06/a08);
  a07=(a07*a06);
  if (res[1]!=0) res[1][2]=a07;
  a25=casadi_sign(a25);
  a07=(a24<=a26);
  a26=(a26<=a24);
  a24=(a26+a07);
  a07=(a07/a24);
  a06=(a25*a07);
  a08=(a19*a06);
  a16=casadi_sign(a16);
  a26=(a26/a24);
  a23=(a23<=a00);
  a23=(a23+a29);
  a29=(a26/a23);
  a29=(a16*a29);
  a24=(a09*a29);
  a08=(a08+a24);
  a24=(a08/a11);
  a10=(a10+a10);
  a04=(a18/a11);
  a03=(a21*a06);
  a28=(a17*a29);
  a03=(a03+a28);
  a28=(a04*a03);
  a05=(a22/a11);
  a01=(a21*a29);
  a27=(a17*a06);
  a01=(a01-a27);
  a27=(a05*a01);
  a02=(a20/a11);
  a06=(a09*a06);
  a29=(a19*a29);
  a06=(a06-a29);
  a29=(a02*a06);
  a27=(a27+a29);
  a28=(a28-a27);
  a27=(a15/a11);
  a08=(a27*a08);
  a28=(a28-a08);
  a08=(a11+a11);
  a28=(a28/a08);
  a29=(a10*a28);
  a24=(a24+a29);
  if (res[1]!=0) res[1][3]=a24;
  a12=(a12+a12);
  a24=(a12*a28);
  a03=(a03/a11);
  a24=(a24-a03);
  if (res[1]!=0) res[1][4]=a24;
  a01=(a01/a11);
  a13=(a13+a13);
  a24=(a13*a28);
  a01=(a01+a24);
  if (res[1]!=0) res[1][5]=a01;
  a06=(a06/a11);
  a14=(a14+a14);
  a28=(a14*a28);
  a06=(a06+a28);
  if (res[1]!=0) res[1][6]=a06;
  if (res[2]!=0) res[2][0]=a00;
  if (res[2]!=0) res[2][1]=a00;
  if (res[2]!=0) res[2][2]=a00;
  if (res[2]!=0) res[2][3]=a00;
  if (res[2]!=0) res[2][4]=a00;
  if (res[2]!=0) res[2][5]=a00;
  if (res[2]!=0) res[2][6]=a00;
  if (res[2]!=0) res[2][7]=a00;
  if (res[2]!=0) res[2][8]=a00;
  a00=2.;
  a06=arg[1]? arg[1][1] : 0;
  a07=(a07*a06);
  a25=(a25*a07);
  a07=(a21*a25);
  a26=(a26*a06);
  a26=(a26/a23);
  a16=(a16*a26);
  a26=(a17*a16);
  a07=(a07+a26);
  a26=(a04*a07);
  a21=(a21*a16);
  a17=(a17*a25);
  a21=(a21-a17);
  a17=(a05*a21);
  a23=(a09*a25);
  a06=(a19*a16);
  a23=(a23-a06);
  a06=(a02*a23);
  a17=(a17+a06);
  a26=(a26-a17);
  a19=(a19*a25);
  a09=(a09*a16);
  a19=(a19+a09);
  a09=(a27*a19);
  a26=(a26-a09);
  a26=(a26/a08);
  a00=(a00*a26);
  a09=(a05*a15);
  a09=(a09/a11);
  a16=(a05/a11);
  a25=(a16*a15);
  a09=(a09+a25);
  a09=(a21*a09);
  a25=(a02*a15);
  a25=(a25/a11);
  a17=(a02/a11);
  a06=(a17*a15);
  a25=(a25+a06);
  a25=(a23*a25);
  a09=(a09+a25);
  a25=(a04*a15);
  a25=(a25/a11);
  a06=(a04/a11);
  a28=(a06*a15);
  a25=(a25+a28);
  a25=(a07*a25);
  a09=(a09-a25);
  a25=(1./a11);
  a28=(a27*a15);
  a28=(a25-a28);
  a28=(a28/a11);
  a01=(a27/a11);
  a24=(a01*a15);
  a28=(a28-a24);
  a28=(a19*a28);
  a09=(a09-a28);
  a09=(a09/a08);
  a26=(a26/a08);
  a28=(a15+a15);
  a28=(a26*a28);
  a09=(a09-a28);
  a09=(a10*a09);
  a09=(a00+a09);
  a28=(a19/a11);
  a28=(a28/a11);
  a15=(a28*a15);
  a09=(a09-a15);
  if (res[2]!=0) res[2][9]=a09;
  a09=(a04*a18);
  a09=(a25-a09);
  a09=(a09/a11);
  a15=(a06*a18);
  a09=(a09-a15);
  a09=(a07*a09);
  a15=(a05*a18);
  a15=(a15/a11);
  a24=(a16*a18);
  a15=(a15+a24);
  a15=(a21*a15);
  a24=(a02*a18);
  a24=(a24/a11);
  a03=(a17*a18);
  a24=(a24+a03);
  a24=(a23*a24);
  a15=(a15+a24);
  a09=(a09+a15);
  a15=(a27*a18);
  a15=(a15/a11);
  a24=(a01*a18);
  a15=(a15+a24);
  a15=(a19*a15);
  a09=(a09+a15);
  a09=(a09/a08);
  a15=(a18+a18);
  a15=(a26*a15);
  a09=(a09-a15);
  a15=(a10*a09);
  a24=(a28*a18);
  a15=(a15-a24);
  if (res[2]!=0) res[2][10]=a15;
  a24=(a27*a22);
  a24=(a24/a11);
  a03=(a01*a22);
  a24=(a24+a03);
  a24=(a19*a24);
  a03=(a04*a22);
  a03=(a03/a11);
  a29=(a06*a22);
  a03=(a03+a29);
  a03=(a07*a03);
  a29=(a05*a22);
  a29=(a25-a29);
  a29=(a29/a11);
  a30=(a16*a22);
  a29=(a29-a30);
  a29=(a21*a29);
  a30=(a02*a22);
  a30=(a30/a11);
  a31=(a17*a22);
  a30=(a30+a31);
  a30=(a23*a30);
  a29=(a29-a30);
  a03=(a03+a29);
  a24=(a24-a03);
  a24=(a24/a08);
  a03=(a22+a22);
  a03=(a26*a03);
  a24=(a24-a03);
  a03=(a10*a24);
  a29=(a28*a22);
  a03=(a03-a29);
  if (res[2]!=0) res[2][11]=a03;
  a27=(a27*a20);
  a27=(a27/a11);
  a01=(a01*a20);
  a27=(a27+a01);
  a19=(a19*a27);
  a04=(a04*a20);
  a04=(a04/a11);
  a06=(a06*a20);
  a04=(a04+a06);
  a04=(a07*a04);
  a02=(a02*a20);
  a25=(a25-a02);
  a25=(a25/a11);
  a17=(a17*a20);
  a25=(a25-a17);
  a25=(a23*a25);
  a05=(a05*a20);
  a05=(a05/a11);
  a16=(a16*a20);
  a05=(a05+a16);
  a05=(a21*a05);
  a25=(a25-a05);
  a04=(a04+a25);
  a19=(a19-a04);
  a19=(a19/a08);
  a08=(a20+a20);
  a26=(a26*a08);
  a19=(a19-a26);
  a10=(a10*a19);
  a28=(a28*a20);
  a10=(a10-a28);
  if (res[2]!=0) res[2][12]=a10;
  if (res[2]!=0) res[2][13]=a15;
  a09=(a12*a09);
  a09=(a00+a09);
  a07=(a07/a11);
  a07=(a07/a11);
  a18=(a07*a18);
  a09=(a09+a18);
  if (res[2]!=0) res[2][14]=a09;
  a09=(a12*a24);
  a18=(a07*a22);
  a09=(a09+a18);
  if (res[2]!=0) res[2][15]=a09;
  a12=(a12*a19);
  a07=(a07*a20);
  a12=(a12+a07);
  if (res[2]!=0) res[2][16]=a12;
  if (res[2]!=0) res[2][17]=a03;
  if (res[2]!=0) res[2][18]=a09;
  a24=(a13*a24);
  a24=(a00+a24);
  a21=(a21/a11);
  a21=(a21/a11);
  a22=(a21*a22);
  a24=(a24-a22);
  if (res[2]!=0) res[2][19]=a24;
  a13=(a13*a19);
  a21=(a21*a20);
  a13=(a13-a21);
  if (res[2]!=0) res[2][20]=a13;
  if (res[2]!=0) res[2][21]=a10;
  if (res[2]!=0) res[2][22]=a12;
  if (res[2]!=0) res[2][23]=a13;
  a14=(a14*a19);
  a00=(a00+a14);
  a23=(a23/a11);
  a23=(a23/a11);
  a23=(a23*a20);
  a00=(a00-a23);
  if (res[2]!=0) res[2][24]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
