/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {0, 0, 1};
static const casadi_int casadi_s3[3] = {88, 1, 1};
static const casadi_int casadi_s4[3] = {6, 1, 1};

/* BlueROV_Heavy_constr_h_fun:(i0[13],i1[8],i2[],i3[13],i4[88])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76;
  a00=-2.;
  a01=arg[0]? arg[0][0] : 0;
  a02=(a00*a01);
  a03=1.;
  a04=2.;
  a05=arg[0]? arg[0][5] : 0;
  a06=arg[0]? arg[0][3] : 0;
  a07=casadi_sq(a06);
  a08=arg[0]? arg[0][4] : 0;
  a09=casadi_sq(a08);
  a07=(a07+a09);
  a09=casadi_sq(a05);
  a07=(a07+a09);
  a09=arg[0]? arg[0][6] : 0;
  a10=casadi_sq(a09);
  a07=(a07+a10);
  a07=sqrt(a07);
  a05=(a05/a07);
  a10=casadi_sq(a05);
  a09=(a09/a07);
  a11=casadi_sq(a09);
  a12=(a10+a11);
  a12=(a04*a12);
  a12=(a03-a12);
  a13=(a02*a12);
  a14=arg[0]? arg[0][1] : 0;
  a00=(a00*a14);
  a08=(a08/a07);
  a15=(a08*a05);
  a06=(a06/a07);
  a07=(a06*a09);
  a16=(a15+a07);
  a16=(a04*a16);
  a17=(a00*a16);
  a13=(a13+a17);
  a17=arg[4]? arg[4][48] : 0;
  a18=(a13*a17);
  a15=(a15-a07);
  a15=(a04*a15);
  a07=(a02*a15);
  a19=casadi_sq(a08);
  a11=(a19+a11);
  a11=(a04*a11);
  a11=(a03-a11);
  a20=(a00*a11);
  a07=(a07+a20);
  a20=arg[4]? arg[4][49] : 0;
  a21=(a07*a20);
  a18=(a18+a21);
  a21=arg[1]? arg[1][0] : 0;
  a18=(a18*a21);
  a22=arg[4]? arg[4][50] : 0;
  a23=(a13*a22);
  a24=arg[4]? arg[4][51] : 0;
  a25=(a07*a24);
  a23=(a23+a25);
  a25=arg[1]? arg[1][1] : 0;
  a23=(a23*a25);
  a18=(a18+a23);
  a23=arg[4]? arg[4][52] : 0;
  a26=(a13*a23);
  a27=arg[4]? arg[4][53] : 0;
  a28=(a07*a27);
  a26=(a26+a28);
  a28=arg[1]? arg[1][2] : 0;
  a26=(a26*a28);
  a18=(a18+a26);
  a26=arg[4]? arg[4][54] : 0;
  a29=(a13*a26);
  a30=arg[4]? arg[4][55] : 0;
  a31=(a07*a30);
  a29=(a29+a31);
  a31=arg[1]? arg[1][3] : 0;
  a29=(a29*a31);
  a18=(a18+a29);
  a29=arg[4]? arg[4][56] : 0;
  a32=(a13*a29);
  a33=arg[4]? arg[4][57] : 0;
  a34=(a07*a33);
  a32=(a32+a34);
  a34=(a08*a09);
  a35=(a06*a05);
  a36=(a34+a35);
  a36=(a04*a36);
  a37=(a02*a36);
  a05=(a05*a09);
  a06=(a06*a08);
  a08=(a05-a06);
  a08=(a04*a08);
  a09=(a00*a08);
  a37=(a37+a09);
  a09=arg[4]? arg[4][58] : 0;
  a38=(a37*a09);
  a32=(a32+a38);
  a38=arg[1]? arg[1][4] : 0;
  a32=(a32*a38);
  a18=(a18+a32);
  a32=arg[4]? arg[4][59] : 0;
  a39=(a13*a32);
  a40=arg[4]? arg[4][60] : 0;
  a41=(a07*a40);
  a39=(a39+a41);
  a41=arg[4]? arg[4][61] : 0;
  a42=(a37*a41);
  a39=(a39+a42);
  a42=arg[1]? arg[1][5] : 0;
  a39=(a39*a42);
  a18=(a18+a39);
  a39=arg[4]? arg[4][62] : 0;
  a43=(a13*a39);
  a44=arg[4]? arg[4][63] : 0;
  a45=(a07*a44);
  a43=(a43+a45);
  a45=arg[4]? arg[4][64] : 0;
  a46=(a37*a45);
  a43=(a43+a46);
  a46=arg[1]? arg[1][6] : 0;
  a43=(a43*a46);
  a18=(a18+a43);
  a43=arg[4]? arg[4][65] : 0;
  a47=(a13*a43);
  a48=arg[4]? arg[4][66] : 0;
  a49=(a07*a48);
  a47=(a47+a49);
  a49=arg[4]? arg[4][67] : 0;
  a50=(a37*a49);
  a47=(a47+a50);
  a50=arg[1]? arg[1][7] : 0;
  a47=(a47*a50);
  a18=(a18+a47);
  a47=arg[0]? arg[0][11] : 0;
  a34=(a34-a35);
  a34=(a04*a34);
  a35=(a47*a34);
  a51=arg[0]? arg[0][12] : 0;
  a52=(a51*a16);
  a35=(a35-a52);
  a52=arg[0]? arg[0][7] : 0;
  a35=(a35*a52);
  a05=(a05+a06);
  a05=(a04*a05);
  a06=(a47*a05);
  a53=(a51*a11);
  a06=(a06-a53);
  a53=arg[0]? arg[0][8] : 0;
  a06=(a06*a53);
  a35=(a35+a06);
  a19=(a19+a10);
  a19=(a04*a19);
  a03=(a03-a19);
  a19=(a47*a03);
  a10=(a51*a08);
  a19=(a19-a10);
  a10=arg[0]? arg[0][9] : 0;
  a19=(a19*a10);
  a35=(a35+a19);
  a19=9.9997012697780208e-01;
  a06=-4.0300000000000002e+00;
  a54=-1.8180000000000000e+01;
  a55=casadi_fabs(a52);
  a54=(a54*a55);
  a06=(a06+a54);
  a06=(a06*a52);
  a54=13.;
  a55=(a54*a10);
  a56=-1.4570000000000000e+01;
  a56=(a56*a10);
  a55=(a55+a56);
  a57=(a55*a47);
  a58=-13.;
  a59=(a58*a53);
  a60=(a59*a51);
  a57=(a57+a60);
  a60=0.;
  a61=arg[0]? arg[0][2] : 0;
  a60=(a60<a61);
  a62=1.4163572500000001e+02;
  a63=(a62*a34);
  a64=(a60?a63:0);
  a65=1.2740000000000001e+02;
  a66=(a65*a34);
  a64=(a64-a66);
  a57=(a57+a64);
  a06=(a06-a57);
  a19=(a19*a06);
  a57=-7.7294988193419290e-03;
  a64=-7.0000000000000007e-02;
  a67=-1.5500000000000000e+00;
  a68=casadi_fabs(a47);
  a68=(a67*a68);
  a68=(a64+a68);
  a68=(a68*a47);
  a69=(a58*a10);
  a56=(a69+a56);
  a56=(a56*a52);
  a70=(a54*a52);
  a71=-5.5000000000000000e+00;
  a71=(a71*a52);
  a72=(a70+a71);
  a72=(a72*a10);
  a56=(a56+a72);
  a72=-3.7000000000000000e-01;
  a72=(a72*a51);
  a73=-1.2000000000000000e-01;
  a74=(a73*a51);
  a72=(a72+a74);
  a74=arg[0]? arg[0][10] : 0;
  a72=(a72*a74);
  a56=(a56+a72);
  a72=2.6000000000000001e-01;
  a72=(a72*a74);
  a75=1.2000000000000000e-01;
  a76=(a75*a74);
  a72=(a72+a76);
  a72=(a72*a51);
  a56=(a56+a72);
  a72=5.9999999999999998e-02;
  a72=(a72*a63);
  a72=(a60?a72:0);
  a63=-1.0999999999999999e-02;
  a66=(a63*a66);
  a72=(a72-a66);
  a56=(a56+a72);
  a68=(a68-a56);
  a57=(a57*a68);
  a19=(a19+a57);
  a57=-1.4570105274459536e-01;
  a56=7.7294988193418309e-03;
  a56=(a56*a06);
  a06=9.9997012697780219e-01;
  a06=(a06*a68);
  a56=(a56+a06);
  a06=3.4888422611106484e-01;
  a56=(a56/a06);
  a57=(a57*a56);
  a19=(a19-a57);
  a57=1.8500552667420507e+01;
  a19=(a19/a57);
  a57=(a12*a19);
  a56=9.9998452018563400e-01;
  a06=-6.2199999999999998e+00;
  a68=-2.1660000000000000e+01;
  a72=casadi_fabs(a53);
  a68=(a68*a72);
  a06=(a06+a68);
  a06=(a06*a53);
  a68=1.4570000000000000e+01;
  a68=(a68*a10);
  a69=(a69+a68);
  a69=(a69*a74);
  a68=5.5000000000000000e+00;
  a68=(a68*a52);
  a70=(a70+a68);
  a70=(a70*a51);
  a69=(a69+a70);
  a70=(a62*a05);
  a68=(a60?a70:0);
  a72=(a65*a05);
  a68=(a68-a72);
  a69=(a69+a68);
  a06=(a06-a69);
  a56=(a56*a06);
  a69=5.5641162018111147e-03;
  a68=casadi_fabs(a74);
  a67=(a67*a68);
  a64=(a64+a67);
  a64=(a64*a74);
  a55=(a55*a53);
  a67=1.2699999999999999e+01;
  a67=(a67*a53);
  a59=(a59+a67);
  a59=(a59*a10);
  a55=(a55+a59);
  a59=3.7000000000000000e-01;
  a59=(a59*a51);
  a75=(a75*a51);
  a59=(a59+a75);
  a59=(a59*a47);
  a55=(a55+a59);
  a59=-2.3000000000000001e-01;
  a59=(a59*a47);
  a73=(a73*a47);
  a59=(a59+a73);
  a59=(a59*a51);
  a55=(a55+a59);
  a59=-5.9999999999999998e-02;
  a59=(a59*a70);
  a59=(a60?a59:0);
  a63=(a63*a72);
  a59=(a59-a63);
  a55=(a55+a59);
  a64=(a64-a55);
  a69=(a69*a64);
  a56=(a56+a69);
  a69=1.4511215054323387e-01;
  a55=-5.5641162018110731e-03;
  a55=(a55*a06);
  a06=9.9998452018563411e-01;
  a06=(a06*a64);
  a55=(a55+a06);
  a06=3.7919844905368194e-01;
  a55=(a55/a06);
  a69=(a69*a55);
  a56=(a56-a69);
  a69=2.5700397837387655e+01;
  a56=(a56/a69);
  a69=(a15*a56);
  a57=(a57+a69);
  a69=-5.1799999999999997e+00;
  a55=-3.6990000000000002e+01;
  a06=casadi_fabs(a10);
  a55=(a55*a06);
  a69=(a69+a55);
  a69=(a69*a10);
  a54=(a54*a53);
  a55=-1.2699999999999999e+01;
  a55=(a55*a53);
  a54=(a54+a55);
  a54=(a54*a74);
  a58=(a58*a52);
  a58=(a58+a71);
  a58=(a58*a47);
  a54=(a54+a58);
  a62=(a62*a03);
  a60=(a60?a62:0);
  a65=(a65*a03);
  a60=(a60-a65);
  a54=(a54+a60);
  a69=(a69-a54);
  a54=2.7570000000000000e+01;
  a69=(a69/a54);
  a54=(a36*a69);
  a57=(a57+a54);
  a35=(a35+a57);
  a02=(a02*a35);
  a57=(a51*a12);
  a54=(a74*a34);
  a57=(a57-a54);
  a57=(a57*a52);
  a54=(a51*a15);
  a60=(a74*a05);
  a54=(a54-a60);
  a54=(a54*a53);
  a57=(a57+a54);
  a51=(a51*a36);
  a54=(a74*a03);
  a51=(a51-a54);
  a51=(a51*a10);
  a57=(a57+a51);
  a51=(a16*a19);
  a54=(a11*a56);
  a51=(a51+a54);
  a54=(a08*a69);
  a51=(a51+a54);
  a57=(a57+a51);
  a00=(a00*a57);
  a02=(a02+a00);
  a00=30.;
  a13=(a13*a52);
  a07=(a07*a53);
  a13=(a13+a07);
  a37=(a37*a10);
  a13=(a13+a37);
  a00=(a00*a13);
  a02=(a02+a00);
  a00=20.;
  a13=1.0889999999999999e+01;
  a37=casadi_sq(a01);
  a07=casadi_sq(a14);
  a07=(a37+a07);
  a13=(a13-a07);
  a13=(a00*a13);
  a02=(a02+a13);
  a18=(a18+a02);
  if (res[0]!=0) res[0][0]=a18;
  a18=(a34*a17);
  a02=(a05*a20);
  a18=(a18+a02);
  a18=(a18*a21);
  a02=(a34*a22);
  a13=(a05*a24);
  a02=(a02+a13);
  a02=(a02*a25);
  a18=(a18+a02);
  a02=(a34*a23);
  a13=(a05*a27);
  a02=(a02+a13);
  a02=(a02*a28);
  a18=(a18+a02);
  a02=(a34*a26);
  a13=(a05*a30);
  a02=(a02+a13);
  a02=(a02*a31);
  a18=(a18+a02);
  a02=(a34*a29);
  a13=(a05*a33);
  a02=(a02+a13);
  a13=(a03*a09);
  a02=(a02+a13);
  a02=(a02*a38);
  a18=(a18+a02);
  a02=(a34*a32);
  a13=(a05*a40);
  a02=(a02+a13);
  a13=(a03*a41);
  a02=(a02+a13);
  a02=(a02*a42);
  a18=(a18+a02);
  a02=(a34*a39);
  a13=(a05*a44);
  a02=(a02+a13);
  a13=(a03*a45);
  a02=(a02+a13);
  a02=(a02*a46);
  a18=(a18+a02);
  a02=(a34*a43);
  a13=(a05*a48);
  a02=(a02+a13);
  a13=(a03*a49);
  a02=(a02+a13);
  a02=(a02*a50);
  a18=(a18+a02);
  a02=(a74*a16);
  a13=(a47*a12);
  a02=(a02-a13);
  a02=(a02*a52);
  a13=(a74*a11);
  a07=(a47*a15);
  a13=(a13-a07);
  a13=(a13*a53);
  a02=(a02+a13);
  a74=(a74*a08);
  a47=(a47*a36);
  a74=(a74-a47);
  a74=(a74*a10);
  a02=(a02+a74);
  a19=(a34*a19);
  a56=(a05*a56);
  a19=(a19+a56);
  a69=(a03*a69);
  a19=(a19+a69);
  a02=(a02+a19);
  a34=(a34*a52);
  a05=(a05*a53);
  a34=(a34+a05);
  a03=(a03*a10);
  a34=(a34+a03);
  a34=(a00*a34);
  a02=(a02+a34);
  a34=15.;
  a03=(a34*a61);
  a03=(a02+a03);
  a03=(a18+a03);
  if (res[0]!=0) res[0][1]=a03;
  a03=1.6000000000000001e+00;
  a03=(a03-a61);
  a03=(a34*a03);
  a02=(a02-a03);
  a18=(a18+a02);
  a18=(-a18);
  if (res[0]!=0) res[0][2]=a18;
  a18=1.8186533479473210e+00;
  a18=(a01-a18);
  a02=(a04*a18);
  a03=(a02*a12);
  a61=-1.0500000000000000e+00;
  a61=(a14-a61);
  a05=(a04*a61);
  a19=(a05*a16);
  a03=(a03+a19);
  a69=(a03*a17);
  a56=(a02*a15);
  a74=(a05*a11);
  a56=(a56+a74);
  a47=(a56*a20);
  a69=(a69+a47);
  a69=(a69*a21);
  a47=(a03*a22);
  a13=(a56*a24);
  a47=(a47+a13);
  a47=(a47*a25);
  a69=(a69+a47);
  a47=(a03*a23);
  a13=(a56*a27);
  a47=(a47+a13);
  a47=(a47*a28);
  a69=(a69+a47);
  a47=(a03*a26);
  a13=(a56*a30);
  a47=(a47+a13);
  a47=(a47*a31);
  a69=(a69+a47);
  a47=(a03*a29);
  a13=(a56*a33);
  a47=(a47+a13);
  a13=(a02*a36);
  a07=(a05*a08);
  a13=(a13+a07);
  a51=(a13*a09);
  a47=(a47+a51);
  a47=(a47*a38);
  a69=(a69+a47);
  a47=(a03*a32);
  a51=(a56*a40);
  a47=(a47+a51);
  a51=(a13*a41);
  a47=(a47+a51);
  a47=(a47*a42);
  a69=(a69+a47);
  a47=(a03*a39);
  a51=(a56*a44);
  a47=(a47+a51);
  a51=(a13*a45);
  a47=(a47+a51);
  a47=(a47*a46);
  a69=(a69+a47);
  a47=(a03*a43);
  a51=(a56*a48);
  a47=(a47+a51);
  a51=(a13*a49);
  a47=(a47+a51);
  a47=(a47*a50);
  a69=(a69+a47);
  a02=(a02*a35);
  a05=(a05*a57);
  a02=(a02+a05);
  a03=(a03*a52);
  a56=(a56*a53);
  a03=(a03+a56);
  a13=(a13*a10);
  a03=(a03+a13);
  a03=(a00*a03);
  a02=(a02+a03);
  a18=casadi_sq(a18);
  a61=casadi_sq(a61);
  a18=(a18+a61);
  a03=3.5999999999999999e-01;
  a18=(a18-a03);
  a18=(a34*a18);
  a02=(a02+a18);
  a69=(a69+a02);
  if (res[0]!=0) res[0][3]=a69;
  a69=(a04*a01);
  a02=(a69*a12);
  a18=2.1000000000000001e+00;
  a14=(a14-a18);
  a18=(a04*a14);
  a16=(a18*a16);
  a02=(a02+a16);
  a16=(a02*a17);
  a13=(a69*a15);
  a11=(a18*a11);
  a13=(a13+a11);
  a11=(a13*a20);
  a16=(a16+a11);
  a16=(a16*a21);
  a11=(a02*a22);
  a56=(a13*a24);
  a11=(a11+a56);
  a11=(a11*a25);
  a16=(a16+a11);
  a11=(a02*a23);
  a56=(a13*a27);
  a11=(a11+a56);
  a11=(a11*a28);
  a16=(a16+a11);
  a11=(a02*a26);
  a56=(a13*a30);
  a11=(a11+a56);
  a11=(a11*a31);
  a16=(a16+a11);
  a11=(a02*a29);
  a56=(a13*a33);
  a11=(a11+a56);
  a56=(a69*a36);
  a08=(a18*a08);
  a56=(a56+a08);
  a08=(a56*a09);
  a11=(a11+a08);
  a11=(a11*a38);
  a16=(a16+a11);
  a11=(a02*a32);
  a08=(a13*a40);
  a11=(a11+a08);
  a08=(a56*a41);
  a11=(a11+a08);
  a11=(a11*a42);
  a16=(a16+a11);
  a11=(a02*a39);
  a08=(a13*a44);
  a11=(a11+a08);
  a08=(a56*a45);
  a11=(a11+a08);
  a11=(a11*a46);
  a16=(a16+a11);
  a11=(a02*a43);
  a08=(a13*a48);
  a11=(a11+a08);
  a08=(a56*a49);
  a11=(a11+a08);
  a11=(a11*a50);
  a16=(a16+a11);
  a69=(a69*a35);
  a18=(a18*a57);
  a69=(a69+a18);
  a02=(a02*a52);
  a13=(a13*a53);
  a02=(a02+a13);
  a56=(a56*a10);
  a02=(a02+a56);
  a02=(a00*a02);
  a69=(a69+a02);
  a14=casadi_sq(a14);
  a37=(a37+a14);
  a37=(a37-a03);
  a37=(a34*a37);
  a69=(a69+a37);
  a16=(a16+a69);
  if (res[0]!=0) res[0][4]=a16;
  a16=-1.8186533479473210e+00;
  a01=(a01-a16);
  a04=(a04*a01);
  a12=(a04*a12);
  a12=(a12+a19);
  a17=(a12*a17);
  a15=(a04*a15);
  a15=(a15+a74);
  a20=(a15*a20);
  a17=(a17+a20);
  a17=(a17*a21);
  a22=(a12*a22);
  a24=(a15*a24);
  a22=(a22+a24);
  a22=(a22*a25);
  a17=(a17+a22);
  a23=(a12*a23);
  a27=(a15*a27);
  a23=(a23+a27);
  a23=(a23*a28);
  a17=(a17+a23);
  a26=(a12*a26);
  a30=(a15*a30);
  a26=(a26+a30);
  a26=(a26*a31);
  a17=(a17+a26);
  a29=(a12*a29);
  a33=(a15*a33);
  a29=(a29+a33);
  a36=(a04*a36);
  a36=(a36+a07);
  a09=(a36*a09);
  a29=(a29+a09);
  a29=(a29*a38);
  a17=(a17+a29);
  a32=(a12*a32);
  a40=(a15*a40);
  a32=(a32+a40);
  a41=(a36*a41);
  a32=(a32+a41);
  a32=(a32*a42);
  a17=(a17+a32);
  a39=(a12*a39);
  a44=(a15*a44);
  a39=(a39+a44);
  a45=(a36*a45);
  a39=(a39+a45);
  a39=(a39*a46);
  a17=(a17+a39);
  a43=(a12*a43);
  a48=(a15*a48);
  a43=(a43+a48);
  a49=(a36*a49);
  a43=(a43+a49);
  a43=(a43*a50);
  a17=(a17+a43);
  a04=(a04*a35);
  a04=(a04+a05);
  a12=(a12*a52);
  a15=(a15*a53);
  a12=(a12+a15);
  a36=(a36*a10);
  a12=(a12+a36);
  a00=(a00*a12);
  a04=(a04+a00);
  a01=casadi_sq(a01);
  a01=(a01+a61);
  a01=(a01-a03);
  a34=(a34*a01);
  a04=(a04+a34);
  a17=(a17+a04);
  if (res[0]!=0) res[0][5]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_constr_h_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
