/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[12] = 
  {13, 2, 0, 3, 7, 0, 1, 2,
  3, 4, 5, 6};

/* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt:(i0[13],i1[13])->(o0[2],o1[13x2,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=0.;
  a01=arg[0]? arg[0][0] : 0;
  a02=arg[1]? arg[1][0] : 0;
  a01=(a01-a02);
  a02=casadi_fabs(a01);
  a03=casadi_fmax(a00,a02);
  a04=arg[0]? arg[0][1] : 0;
  a05=arg[1]? arg[1][1] : 0;
  a04=(a04-a05);
  a05=casadi_fabs(a04);
  a06=casadi_fmax(a03,a05);
  a07=arg[0]? arg[0][2] : 0;
  a08=arg[1]? arg[1][2] : 0;
  a07=(a07-a08);
  a08=casadi_fabs(a07);
  a09=casadi_fmax(a06,a08);
  if (res[0]!=0) res[0][0]=a09;
  a09=arg[1]? arg[1][4] : 0;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a12=arg[0]? arg[0][4] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][5] : 0;
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a14=arg[0]? arg[0][6] : 0;
  a15=casadi_sq(a14);
  a11=(a11+a15);
  a11=sqrt(a11);
  a15=(a10/a11);
  a16=(a09*a15);
  a17=arg[1]? arg[1][3] : 0;
  a18=(a12/a11);
  a19=(a17*a18);
  a16=(a16-a19);
  a19=arg[1]? arg[1][5] : 0;
  a20=(a14/a11);
  a21=(a19*a20);
  a16=(a16-a21);
  a21=arg[1]? arg[1][6] : 0;
  a22=(a13/a11);
  a23=(a21*a22);
  a16=(a16+a23);
  a23=casadi_fabs(a16);
  a24=casadi_fmax(a00,a23);
  a25=(a09*a20);
  a26=(a17*a22);
  a25=(a25-a26);
  a26=(a19*a15);
  a25=(a25+a26);
  a26=(a21*a18);
  a25=(a25-a26);
  a26=casadi_fabs(a25);
  a27=casadi_fmax(a24,a26);
  if (res[0]!=0) res[0][1]=a27;
  a01=casadi_sign(a01);
  a27=(a05<=a03);
  a03=(a03<=a05);
  a05=(a27+a03);
  a27=(a27/a05);
  a28=(a08<=a06);
  a06=(a06<=a08);
  a08=(a28+a06);
  a28=(a28/a08);
  a27=(a27*a28);
  a02=(a02<=a00);
  a29=1.;
  a02=(a02+a29);
  a27=(a27/a02);
  a01=(a01*a27);
  if (res[1]!=0) res[1][0]=a01;
  a04=casadi_sign(a04);
  a03=(a03/a05);
  a03=(a03*a28);
  a04=(a04*a03);
  if (res[1]!=0) res[1][1]=a04;
  a07=casadi_sign(a07);
  a06=(a06/a08);
  a07=(a07*a06);
  if (res[1]!=0) res[1][2]=a07;
  a25=casadi_sign(a25);
  a07=(a24<=a26);
  a26=(a26<=a24);
  a24=(a26+a07);
  a07=(a07/a24);
  a25=(a25*a07);
  a07=(a19*a25);
  a16=casadi_sign(a16);
  a26=(a26/a24);
  a23=(a23<=a00);
  a23=(a23+a29);
  a26=(a26/a23);
  a16=(a16*a26);
  a26=(a09*a16);
  a07=(a07+a26);
  a26=(a07/a11);
  a10=(a10+a10);
  a18=(a18/a11);
  a23=(a21*a25);
  a29=(a17*a16);
  a23=(a23+a29);
  a18=(a18*a23);
  a22=(a22/a11);
  a21=(a21*a16);
  a17=(a17*a25);
  a21=(a21-a17);
  a22=(a22*a21);
  a20=(a20/a11);
  a09=(a09*a25);
  a19=(a19*a16);
  a09=(a09-a19);
  a20=(a20*a09);
  a22=(a22+a20);
  a18=(a18-a22);
  a15=(a15/a11);
  a15=(a15*a07);
  a18=(a18-a15);
  a15=(a11+a11);
  a18=(a18/a15);
  a10=(a10*a18);
  a26=(a26+a10);
  if (res[1]!=0) res[1][3]=a26;
  a12=(a12+a12);
  a12=(a12*a18);
  a23=(a23/a11);
  a12=(a12-a23);
  if (res[1]!=0) res[1][4]=a12;
  a21=(a21/a11);
  a13=(a13+a13);
  a13=(a13*a18);
  a21=(a21+a13);
  if (res[1]!=0) res[1][5]=a21;
  a09=(a09/a11);
  a14=(a14+a14);
  a14=(a14*a18);
  a09=(a09+a14);
  if (res[1]!=0) res[1][6]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
