/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {88, 1, 1};
static const casadi_int casadi_s3[3] = {21, 1, 1};

/* BlueROV_Heavy_expl_vde_adj:(i0[13],i1[13],i2[8],i3[13],i4[88])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a01=5.0000000000000000e-01;
  a02=arg[0]? arg[0][12] : 0;
  a03=arg[1]? arg[1][6] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a05=arg[0]? arg[0][11] : 0;
  a06=arg[1]? arg[1][5] : 0;
  a07=(a05*a06);
  a07=(a01*a07);
  a04=(a04+a07);
  a07=arg[0]? arg[0][10] : 0;
  a08=arg[1]? arg[1][4] : 0;
  a09=(a07*a08);
  a09=(a01*a09);
  a04=(a04+a09);
  a09=arg[0]? arg[0][4] : 0;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a12=casadi_sq(a09);
  a11=(a11+a12);
  a12=arg[0]? arg[0][5] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][6] : 0;
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a11=sqrt(a11);
  a14=(a09/a11);
  a15=2.;
  a16=1.2740000000000001e+02;
  a17=-1.0999999999999999e-02;
  a18=9.9998452018563411e-01;
  a19=2.6371415877242503e+00;
  a20=arg[1]? arg[1][10] : 0;
  a21=1.4511215054323387e-01;
  a22=3.8909903509168640e-02;
  a23=arg[1]? arg[1][8] : 0;
  a22=(a22*a23);
  a21=(a21*a22);
  a20=(a20-a21);
  a19=(a19*a20);
  a18=(a18*a19);
  a20=5.5641162018111147e-03;
  a20=(a20*a22);
  a18=(a18+a20);
  a20=(a17*a18);
  a21=-5.5641162018110731e-03;
  a21=(a21*a19);
  a19=9.9998452018563400e-01;
  a19=(a19*a22);
  a21=(a21+a19);
  a20=(a20+a21);
  a20=(a16*a20);
  a19=arg[0]? arg[0][2] : 0;
  a00=(a00<a19);
  a19=1.4163572500000001e+02;
  a22=-5.9999999999999998e-02;
  a22=(a22*a18);
  a22=(a22+a21);
  a22=(a19*a22);
  a22=(-a22);
  a22=(a00?a22:0);
  a20=(a20+a22);
  a22=arg[0]? arg[0][8] : 0;
  a23=arg[1]? arg[1][2] : 0;
  a24=(a22*a23);
  a20=(a20+a24);
  a20=(a15*a20);
  a24=(a14*a20);
  a04=(a04+a24);
  a24=(a12/a11);
  a25=9.9997012697780219e-01;
  a26=2.8662803450496415e+00;
  a27=arg[1]? arg[1][11] : 0;
  a28=-1.4570105274459536e-01;
  a29=5.4052439296097411e-02;
  a30=arg[1]? arg[1][7] : 0;
  a29=(a29*a30);
  a28=(a28*a29);
  a27=(a27-a28);
  a26=(a26*a27);
  a25=(a25*a26);
  a27=-7.7294988193419290e-03;
  a27=(a27*a29);
  a25=(a25+a27);
  a17=(a17*a25);
  a27=7.7294988193418309e-03;
  a27=(a27*a26);
  a26=9.9997012697780208e-01;
  a26=(a26*a29);
  a27=(a27+a26);
  a17=(a17+a27);
  a17=(a16*a17);
  a26=5.9999999999999998e-02;
  a26=(a26*a25);
  a26=(a26+a27);
  a26=(a19*a26);
  a26=(-a26);
  a26=(a00?a26:0);
  a17=(a17+a26);
  a26=arg[0]? arg[0][7] : 0;
  a29=(a26*a23);
  a17=(a17+a29);
  a17=(a15*a17);
  a29=(a24*a17);
  a04=(a04-a29);
  a29=arg[0]? arg[0][9] : 0;
  a28=arg[1]? arg[1][1] : 0;
  a30=(a29*a28);
  a30=(a15*a30);
  a31=(a14*a30);
  a04=(a04-a31);
  a31=(a13/a11);
  a32=(a26*a28);
  a32=(a15*a32);
  a33=(a31*a32);
  a04=(a04+a33);
  a33=arg[1]? arg[1][0] : 0;
  a34=(a29*a33);
  a34=(a15*a34);
  a35=(a24*a34);
  a04=(a04+a35);
  a35=(a22*a33);
  a35=(a15*a35);
  a36=(a31*a35);
  a04=(a04-a36);
  a36=(a04/a11);
  a37=(a10+a10);
  a10=(a10/a11);
  a38=(a10/a11);
  a38=(a38*a04);
  a04=(a14/a11);
  a39=(a05*a03);
  a39=(a01*a39);
  a40=(a02*a06);
  a40=(a01*a40);
  a39=(a39-a40);
  a40=arg[1]? arg[1][3] : 0;
  a41=(a07*a40);
  a41=(a01*a41);
  a39=(a39-a41);
  a41=(a14+a14);
  a42=3.6271309394269133e-02;
  a43=arg[1]? arg[1][9] : 0;
  a42=(a42*a43);
  a16=(a16*a42);
  a19=(a19*a42);
  a19=(-a19);
  a00=(a00?a19:0);
  a16=(a16+a00);
  a00=(a29*a23);
  a16=(a16+a00);
  a16=(a15*a16);
  a00=(a41*a16);
  a39=(a39-a00);
  a00=(a10*a20);
  a39=(a39+a00);
  a00=(a31*a17);
  a39=(a39+a00);
  a00=(a10*a30);
  a39=(a39-a00);
  a00=(a22*a28);
  a00=(a15*a00);
  a41=(a41*a00);
  a39=(a39-a41);
  a41=(a24*a32);
  a39=(a39+a41);
  a41=(a31*a34);
  a39=(a39+a41);
  a41=(a24*a35);
  a39=(a39+a41);
  a04=(a04*a39);
  a38=(a38+a04);
  a04=(a31/a11);
  a41=(a07*a06);
  a41=(a01*a41);
  a19=(a05*a08);
  a19=(a01*a19);
  a41=(a41-a19);
  a19=(a02*a40);
  a19=(a01*a19);
  a41=(a41-a19);
  a19=(a24*a20);
  a41=(a41+a19);
  a19=(a14*a17);
  a41=(a41+a19);
  a19=(a24*a30);
  a41=(a41+a19);
  a19=(a31+a31);
  a00=(a19*a00);
  a41=(a41-a00);
  a00=(a10*a32);
  a41=(a41+a00);
  a00=(a14*a34);
  a41=(a41+a00);
  a00=(a10*a35);
  a41=(a41-a00);
  a00=(a26*a33);
  a00=(a15*a00);
  a19=(a19*a00);
  a41=(a41-a19);
  a04=(a04*a41);
  a38=(a38+a04);
  a04=(a24/a11);
  a19=(a02*a08);
  a19=(a01*a19);
  a43=(a07*a03);
  a43=(a01*a43);
  a19=(a19-a43);
  a43=(a05*a40);
  a43=(a01*a43);
  a19=(a19-a43);
  a43=(a24+a24);
  a16=(a43*a16);
  a19=(a19-a16);
  a20=(a31*a20);
  a19=(a19+a20);
  a17=(a10*a17);
  a19=(a19-a17);
  a30=(a31*a30);
  a19=(a19+a30);
  a32=(a14*a32);
  a19=(a19+a32);
  a34=(a10*a34);
  a19=(a19+a34);
  a35=(a14*a35);
  a19=(a19+a35);
  a43=(a43*a00);
  a19=(a19-a43);
  a04=(a04*a19);
  a38=(a38+a04);
  a04=(a11+a11);
  a38=(a38/a04);
  a37=(a37*a38);
  a36=(a36-a37);
  if (res[0]!=0) res[0][3]=a36;
  a39=(a39/a11);
  a09=(a09+a09);
  a09=(a09*a38);
  a39=(a39-a09);
  if (res[0]!=0) res[0][4]=a39;
  a19=(a19/a11);
  a12=(a12+a12);
  a12=(a12*a38);
  a19=(a19-a12);
  if (res[0]!=0) res[0][5]=a19;
  a41=(a41/a11);
  a13=(a13+a13);
  a13=(a13*a38);
  a41=(a41-a13);
  if (res[0]!=0) res[0][6]=a41;
  a41=-4.0300000000000002e+00;
  a13=-1.8180000000000000e+01;
  a38=casadi_fabs(a26);
  a38=(a13*a38);
  a41=(a41+a38);
  a41=(a41*a27);
  a38=-5.5000000000000000e+00;
  a11=2.0408163265306123e+00;
  a19=arg[1]? arg[1][12] : 0;
  a11=(a11*a19);
  a19=(a22*a11);
  a12=(a38*a19);
  a39=-13.;
  a19=(a39*a19);
  a12=(a12+a19);
  a19=13.;
  a09=(a19*a22);
  a36=1.2699999999999999e+01;
  a37=(a36*a22);
  a04=(a09+a37);
  a04=(a04*a11);
  a12=(a12+a04);
  a04=(a05*a42);
  a43=(a38*a04);
  a12=(a12+a43);
  a04=(a39*a04);
  a12=(a12+a04);
  a04=5.5000000000000000e+00;
  a43=(a02*a21);
  a00=(a04*a43);
  a12=(a12+a00);
  a43=(a19*a43);
  a12=(a12+a43);
  a43=(a29*a25);
  a00=(a38*a43);
  a12=(a12+a00);
  a43=(a19*a43);
  a12=(a12+a43);
  a43=(a39*a29);
  a00=-1.4570000000000000e+01;
  a35=(a00*a29);
  a34=(a43+a35);
  a34=(a34*a25);
  a12=(a12+a34);
  a41=(a41-a12);
  a12=casadi_sign(a26);
  a34=(a26*a27);
  a13=(a13*a34);
  a12=(a12*a13);
  a41=(a41+a12);
  a12=(a14*a31);
  a13=(a10*a24);
  a34=(a12-a13);
  a34=(a15*a34);
  a34=(a34*a23);
  a41=(a41+a34);
  a34=(a14*a24);
  a32=(a10*a31);
  a30=(a34+a32);
  a30=(a15*a30);
  a30=(a30*a28);
  a41=(a41+a30);
  a30=1.;
  a17=casadi_sq(a24);
  a20=casadi_sq(a31);
  a16=(a17+a20);
  a16=(a15*a16);
  a16=(a30-a16);
  a16=(a16*a33);
  a41=(a41+a16);
  if (res[0]!=0) res[0][7]=a41;
  a41=-6.2199999999999998e+00;
  a16=-2.1660000000000000e+01;
  a44=casadi_fabs(a22);
  a44=(a16*a44);
  a41=(a41+a44);
  a41=(a41*a21);
  a44=(a39*a26);
  a38=(a38*a26);
  a44=(a44+a38);
  a45=(a44*a11);
  a46=(a26*a11);
  a47=(a36*a46);
  a45=(a45+a47);
  a46=(a19*a46);
  a45=(a45+a46);
  a46=-1.2699999999999999e+01;
  a47=(a07*a42);
  a48=(a46*a47);
  a45=(a45+a48);
  a47=(a19*a47);
  a45=(a45+a47);
  a47=(a29*a18);
  a36=(a36*a47);
  a45=(a45+a36);
  a47=(a39*a47);
  a45=(a45+a47);
  a47=(a19*a29);
  a47=(a47+a35);
  a35=(a47*a18);
  a45=(a45+a35);
  a41=(a41-a45);
  a45=casadi_sign(a22);
  a35=(a22*a21);
  a16=(a16*a35);
  a45=(a45*a16);
  a41=(a41+a45);
  a45=(a02*a27);
  a45=(a39*a45);
  a41=(a41-a45);
  a45=(a24*a31);
  a16=(a10*a14);
  a35=(a45+a16);
  a35=(a15*a35);
  a35=(a35*a23);
  a41=(a41+a35);
  a35=casadi_sq(a14);
  a20=(a35+a20);
  a20=(a15*a20);
  a20=(a30-a20);
  a20=(a20*a28);
  a41=(a41+a20);
  a34=(a34-a32);
  a34=(a15*a34);
  a34=(a34*a33);
  a41=(a41+a34);
  if (res[0]!=0) res[0][8]=a41;
  a41=-5.1799999999999997e+00;
  a34=-3.6990000000000002e+01;
  a32=casadi_fabs(a29);
  a32=(a34*a32);
  a41=(a41+a32);
  a41=(a41*a42);
  a32=casadi_sign(a29);
  a20=(a29*a42);
  a34=(a34*a20);
  a32=(a32*a34);
  a41=(a41+a32);
  a32=(a39*a22);
  a37=(a32+a37);
  a37=(a37*a18);
  a41=(a41-a37);
  a37=(a22*a18);
  a34=(a00*a37);
  a41=(a41-a34);
  a37=(a19*a37);
  a41=(a41-a37);
  a37=1.4570000000000000e+01;
  a34=(a07*a21);
  a20=(a37*a34);
  a41=(a41-a20);
  a34=(a39*a34);
  a41=(a41-a34);
  a34=(a19*a26);
  a38=(a34+a38);
  a38=(a38*a25);
  a41=(a41-a38);
  a38=(a26*a25);
  a20=(a00*a38);
  a41=(a41-a20);
  a39=(a39*a38);
  a41=(a41-a39);
  a39=(a05*a27);
  a00=(a00*a39);
  a41=(a41-a00);
  a19=(a19*a39);
  a41=(a41-a19);
  a35=(a35+a17);
  a35=(a15*a35);
  a30=(a30-a35);
  a30=(a30*a23);
  a41=(a41+a30);
  a45=(a45-a16);
  a45=(a15*a45);
  a45=(a45*a28);
  a41=(a41+a45);
  a12=(a12+a13);
  a15=(a15*a12);
  a15=(a15*a33);
  a41=(a41+a15);
  if (res[0]!=0) res[0][9]=a41;
  a41=-7.0000000000000007e-02;
  a15=-1.5500000000000000e+00;
  a33=casadi_fabs(a07);
  a33=(a15*a33);
  a33=(a41+a33);
  a33=(a33*a18);
  a12=-1.2000000000000000e-01;
  a13=(a05*a11);
  a45=(a12*a13);
  a28=-2.6000000000000001e-01;
  a13=(a28*a13);
  a45=(a45+a13);
  a13=2.3000000000000001e-01;
  a16=(a13*a05);
  a30=1.2000000000000000e-01;
  a23=(a30*a05);
  a16=(a16+a23);
  a16=(a16*a11);
  a45=(a45+a16);
  a46=(a46*a22);
  a09=(a09+a46);
  a09=(a09*a42);
  a45=(a45+a09);
  a33=(a33-a45);
  a45=casadi_sign(a07);
  a09=(a07*a18);
  a09=(a15*a09);
  a45=(a45*a09);
  a33=(a33+a45);
  a37=(a37*a29);
  a43=(a43+a37);
  a43=(a43*a21);
  a33=(a33-a43);
  a43=(a02*a25);
  a37=(a30*a43);
  a33=(a33-a37);
  a37=2.6000000000000001e-01;
  a43=(a37*a43);
  a33=(a33-a43);
  a43=-3.7000000000000000e-01;
  a29=(a43*a02);
  a45=(a12*a02);
  a29=(a29+a45);
  a29=(a29*a25);
  a33=(a33-a29);
  a24=(a01*a24);
  a29=(a24*a03);
  a33=(a33-a29);
  a31=(a01*a31);
  a29=(a31*a06);
  a33=(a33+a29);
  a10=(a01*a10);
  a29=(a10*a08);
  a33=(a33+a29);
  a01=(a01*a14);
  a14=(a01*a40);
  a33=(a33-a14);
  if (res[0]!=0) res[0][10]=a33;
  a33=casadi_fabs(a05);
  a33=(a15*a33);
  a33=(a41+a33);
  a33=(a33*a25);
  a28=(a28*a07);
  a14=(a12*a07);
  a28=(a28+a14);
  a28=(a28*a11);
  a14=(a07*a11);
  a29=(a30*a14);
  a28=(a28+a29);
  a13=(a13*a14);
  a28=(a28+a13);
  a44=(a44*a42);
  a28=(a28+a44);
  a44=(a02*a18);
  a13=(a12*a44);
  a28=(a28+a13);
  a13=-2.3000000000000001e-01;
  a44=(a13*a44);
  a28=(a28+a44);
  a44=3.7000000000000000e-01;
  a14=(a44*a02);
  a29=(a30*a02);
  a14=(a14+a29);
  a14=(a14*a18);
  a28=(a28+a14);
  a33=(a33-a28);
  a28=casadi_sign(a05);
  a14=(a05*a25);
  a14=(a15*a14);
  a28=(a28*a14);
  a33=(a33+a28);
  a47=(a47*a27);
  a33=(a33-a47);
  a47=(a01*a03);
  a33=(a33+a47);
  a47=(a10*a06);
  a33=(a33+a47);
  a47=(a31*a08);
  a33=(a33-a47);
  a47=(a24*a40);
  a33=(a33-a47);
  if (res[0]!=0) res[0][11]=a33;
  a33=casadi_fabs(a02);
  a33=(a15*a33);
  a41=(a41+a33);
  a41=(a41*a11);
  a33=casadi_sign(a02);
  a02=(a02*a11);
  a15=(a15*a02);
  a33=(a33*a15);
  a41=(a41+a33);
  a13=(a13*a05);
  a33=(a12*a05);
  a13=(a13+a33);
  a13=(a13*a18);
  a41=(a41-a13);
  a05=(a05*a18);
  a13=(a30*a05);
  a41=(a41-a13);
  a44=(a44*a05);
  a41=(a41-a44);
  a04=(a04*a26);
  a34=(a34+a04);
  a34=(a34*a21);
  a41=(a41-a34);
  a37=(a37*a07);
  a34=(a30*a07);
  a37=(a37+a34);
  a37=(a37*a25);
  a41=(a41-a37);
  a07=(a07*a25);
  a37=(a12*a07);
  a41=(a41-a37);
  a43=(a43*a07);
  a41=(a41-a43);
  a32=(a32*a27);
  a41=(a41-a32);
  a10=(a10*a03);
  a41=(a41+a10);
  a01=(a01*a06);
  a41=(a41-a01);
  a24=(a24*a08);
  a41=(a41+a24);
  a31=(a31*a40);
  a41=(a41-a31);
  if (res[0]!=0) res[0][12]=a41;
  a41=arg[4]? arg[4][0] : 0;
  a31=-1.8880000000000000e-01;
  a31=(a31*a11);
  a40=6.0100000000000001e-02;
  a24=(a40*a18);
  a08=(a31+a24);
  a01=-7.0709999999999995e-01;
  a06=(a01*a21);
  a08=(a08+a06);
  a40=(a40*a25);
  a08=(a08+a40);
  a10=7.0709999999999995e-01;
  a03=(a10*a27);
  a08=(a08+a03);
  a41=(a41*a08);
  if (res[0]!=0) res[0][13]=a41;
  a41=arg[4]? arg[4][1] : 0;
  a08=1.8880000000000000e-01;
  a08=(a08*a11);
  a11=-6.0100000000000001e-02;
  a32=(a11*a18);
  a43=(a08+a32);
  a10=(a10*a21);
  a43=(a43+a10);
  a43=(a43+a40);
  a43=(a43+a03);
  a41=(a41*a43);
  if (res[0]!=0) res[0][14]=a41;
  a41=arg[4]? arg[4][2] : 0;
  a08=(a08+a24);
  a08=(a08+a06);
  a11=(a11*a25);
  a08=(a08+a11);
  a01=(a01*a27);
  a08=(a08+a01);
  a41=(a41*a08);
  if (res[0]!=0) res[0][15]=a41;
  a41=arg[4]? arg[4][3] : 0;
  a31=(a31+a32);
  a31=(a31+a10);
  a31=(a31+a11);
  a31=(a31+a01);
  a41=(a41*a31);
  if (res[0]!=0) res[0][16]=a41;
  a41=arg[4]? arg[4][4] : 0;
  a31=-2.1800000000000000e-01;
  a31=(a31*a18);
  a01=(a31-a42);
  a30=(a30*a25);
  a01=(a01+a30);
  a41=(a41*a01);
  if (res[0]!=0) res[0][17]=a41;
  a41=arg[4]? arg[4][5] : 0;
  a31=(a42+a31);
  a12=(a12*a25);
  a31=(a31+a12);
  a41=(a41*a31);
  if (res[0]!=0) res[0][18]=a41;
  a41=arg[4]? arg[4][6] : 0;
  a31=2.1800000000000000e-01;
  a31=(a31*a18);
  a18=(a42+a31);
  a18=(a18+a30);
  a41=(a41*a18);
  if (res[0]!=0) res[0][19]=a41;
  a41=arg[4]? arg[4][7] : 0;
  a31=(a31-a42);
  a31=(a31+a12);
  a41=(a41*a31);
  if (res[0]!=0) res[0][20]=a41;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_expl_vde_adj_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
