/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_p_global_precompute_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {88, 1, 1};

/* BlueROV_Heavy_p_global_precompute_fun:(i0[8])->(o0[88]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32;
  a00=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][3]=a03;
  a04=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][4]=a04;
  a05=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][5]=a05;
  a06=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][6]=a06;
  a07=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][7]=a07;
  a08=5.4052439296097411e-02;
  a09=9.9997012697780208e-01;
  a10=7.0709999999999995e-01;
  a11=(a10*a00);
  a12=(a09*a11);
  a13=-7.7294988193419290e-03;
  a14=6.0100000000000001e-02;
  a15=(a14*a00);
  a16=(a13*a15);
  a12=(a12+a16);
  a16=-1.4570105274459536e-01;
  a17=2.8662803450496415e+00;
  a18=7.7294988193418309e-03;
  a11=(a18*a11);
  a19=9.9997012697780219e-01;
  a20=(a19*a15);
  a11=(a11+a20);
  a11=(a17*a11);
  a20=(a16*a11);
  a12=(a12-a20);
  a12=(a08*a12);
  if (res[0]!=0) res[0][8]=a12;
  a12=3.8909903509168640e-02;
  a20=9.9998452018563400e-01;
  a21=-7.0709999999999995e-01;
  a22=(a21*a00);
  a23=(a20*a22);
  a24=5.5641162018111147e-03;
  a25=(a24*a15);
  a23=(a23+a25);
  a25=1.4511215054323387e-01;
  a26=2.6371415877242503e+00;
  a27=-5.5641162018110731e-03;
  a22=(a27*a22);
  a28=9.9998452018563411e-01;
  a15=(a28*a15);
  a22=(a22+a15);
  a22=(a26*a22);
  a15=(a25*a22);
  a23=(a23-a15);
  a23=(a12*a23);
  if (res[0]!=0) res[0][9]=a23;
  if (res[0]!=0) res[0][10]=a22;
  if (res[0]!=0) res[0][11]=a11;
  a11=2.0408163265306123e+00;
  a22=-1.8880000000000000e-01;
  a23=(a22*a00);
  a23=(a11*a23);
  if (res[0]!=0) res[0][12]=a23;
  a23=(a10*a01);
  a15=(a09*a23);
  a29=(a14*a01);
  a30=(a13*a29);
  a15=(a15+a30);
  a30=(a18*a23);
  a29=(a19*a29);
  a30=(a30+a29);
  a30=(a17*a30);
  a29=(a16*a30);
  a15=(a15-a29);
  a15=(a08*a15);
  if (res[0]!=0) res[0][13]=a15;
  a15=(a20*a23);
  a29=-6.0100000000000001e-02;
  a31=(a29*a01);
  a32=(a24*a31);
  a15=(a15+a32);
  a23=(a27*a23);
  a31=(a28*a31);
  a23=(a23+a31);
  a23=(a26*a23);
  a31=(a25*a23);
  a15=(a15-a31);
  a15=(a12*a15);
  if (res[0]!=0) res[0][14]=a15;
  if (res[0]!=0) res[0][15]=a23;
  if (res[0]!=0) res[0][16]=a30;
  a30=1.8880000000000000e-01;
  a23=(a30*a01);
  a23=(a11*a23);
  if (res[0]!=0) res[0][17]=a23;
  a23=(a21*a02);
  a15=(a09*a23);
  a31=(a29*a02);
  a32=(a13*a31);
  a15=(a15+a32);
  a32=(a18*a23);
  a31=(a19*a31);
  a32=(a32+a31);
  a32=(a17*a32);
  a31=(a16*a32);
  a15=(a15-a31);
  a15=(a08*a15);
  if (res[0]!=0) res[0][18]=a15;
  a15=(a20*a23);
  a14=(a14*a02);
  a31=(a24*a14);
  a15=(a15+a31);
  a23=(a27*a23);
  a14=(a28*a14);
  a23=(a23+a14);
  a23=(a26*a23);
  a14=(a25*a23);
  a15=(a15-a14);
  a15=(a12*a15);
  if (res[0]!=0) res[0][19]=a15;
  if (res[0]!=0) res[0][20]=a23;
  if (res[0]!=0) res[0][21]=a32;
  a30=(a30*a02);
  a30=(a11*a30);
  if (res[0]!=0) res[0][22]=a30;
  a21=(a21*a03);
  a09=(a09*a21);
  a29=(a29*a03);
  a30=(a13*a29);
  a09=(a09+a30);
  a18=(a18*a21);
  a21=(a19*a29);
  a18=(a18+a21);
  a18=(a17*a18);
  a21=(a16*a18);
  a09=(a09-a21);
  a09=(a08*a09);
  if (res[0]!=0) res[0][23]=a09;
  a10=(a10*a03);
  a20=(a20*a10);
  a09=(a24*a29);
  a20=(a20+a09);
  a27=(a27*a10);
  a29=(a28*a29);
  a27=(a27+a29);
  a27=(a26*a27);
  a29=(a25*a27);
  a20=(a20-a29);
  a20=(a12*a20);
  if (res[0]!=0) res[0][24]=a20;
  if (res[0]!=0) res[0][25]=a27;
  if (res[0]!=0) res[0][26]=a18;
  a22=(a22*a03);
  a11=(a11*a22);
  if (res[0]!=0) res[0][27]=a11;
  a11=1.2000000000000000e-01;
  a22=(a11*a04);
  a18=(a13*a22);
  a22=(a19*a22);
  a22=(a17*a22);
  a27=(a16*a22);
  a18=(a18-a27);
  a18=(a08*a18);
  if (res[0]!=0) res[0][28]=a18;
  a18=-2.1800000000000000e-01;
  a27=(a18*a04);
  a20=(a24*a27);
  a27=(a28*a27);
  a27=(a26*a27);
  a29=(a25*a27);
  a20=(a20-a29);
  a20=(a12*a20);
  if (res[0]!=0) res[0][29]=a20;
  a20=3.6271309394269133e-02;
  a29=(a20*a04);
  if (res[0]!=0) res[0][30]=a29;
  if (res[0]!=0) res[0][31]=a27;
  if (res[0]!=0) res[0][32]=a22;
  a22=-1.2000000000000000e-01;
  a27=(a22*a05);
  a29=(a13*a27);
  a27=(a19*a27);
  a27=(a17*a27);
  a10=(a16*a27);
  a29=(a29-a10);
  a29=(a08*a29);
  if (res[0]!=0) res[0][33]=a29;
  a18=(a18*a05);
  a29=(a24*a18);
  a18=(a28*a18);
  a18=(a26*a18);
  a10=(a25*a18);
  a29=(a29-a10);
  a29=(a12*a29);
  if (res[0]!=0) res[0][34]=a29;
  a29=(a20*a05);
  if (res[0]!=0) res[0][35]=a29;
  if (res[0]!=0) res[0][36]=a18;
  if (res[0]!=0) res[0][37]=a27;
  a11=(a11*a06);
  a27=(a13*a11);
  a11=(a19*a11);
  a11=(a17*a11);
  a18=(a16*a11);
  a27=(a27-a18);
  a27=(a08*a27);
  if (res[0]!=0) res[0][38]=a27;
  a27=2.1800000000000000e-01;
  a18=(a27*a06);
  a10=(a24*a18);
  a18=(a28*a18);
  a18=(a26*a18);
  a09=(a25*a18);
  a10=(a10-a09);
  a10=(a12*a10);
  if (res[0]!=0) res[0][39]=a10;
  a10=(a20*a06);
  if (res[0]!=0) res[0][40]=a10;
  if (res[0]!=0) res[0][41]=a18;
  if (res[0]!=0) res[0][42]=a11;
  a22=(a22*a07);
  a13=(a13*a22);
  a19=(a19*a22);
  a17=(a17*a19);
  a16=(a16*a17);
  a13=(a13-a16);
  a08=(a08*a13);
  if (res[0]!=0) res[0][43]=a08;
  a27=(a27*a07);
  a24=(a24*a27);
  a28=(a28*a27);
  a26=(a26*a28);
  a25=(a25*a26);
  a24=(a24-a25);
  a12=(a12*a24);
  if (res[0]!=0) res[0][44]=a12;
  a20=(a20*a07);
  if (res[0]!=0) res[0][45]=a20;
  if (res[0]!=0) res[0][46]=a26;
  if (res[0]!=0) res[0][47]=a17;
  a17=3.9674223660174035e-02;
  a26=(a17*a00);
  if (res[0]!=0) res[0][48]=a26;
  a20=-2.8453219320282656e-02;
  a00=(a20*a00);
  if (res[0]!=0) res[0][49]=a00;
  a17=(a17*a01);
  if (res[0]!=0) res[0][50]=a17;
  a12=2.8453219320282656e-02;
  a01=(a12*a01);
  if (res[0]!=0) res[0][51]=a01;
  a24=-3.9674223660174035e-02;
  a25=(a24*a02);
  if (res[0]!=0) res[0][52]=a25;
  a20=(a20*a02);
  if (res[0]!=0) res[0][53]=a20;
  a24=(a24*a03);
  if (res[0]!=0) res[0][54]=a24;
  a12=(a12*a03);
  if (res[0]!=0) res[0][55]=a12;
  a03=2.6585892651557015e-03;
  a02=(a03*a04);
  if (res[0]!=0) res[0][56]=a02;
  a28=3.1987929671703523e-03;
  a27=(a28*a04);
  if (res[0]!=0) res[0][57]=a27;
  a08=-3.6271309394269133e-02;
  a04=(a08*a04);
  if (res[0]!=0) res[0][58]=a04;
  a13=-2.6585892651557015e-03;
  a16=(a13*a05);
  if (res[0]!=0) res[0][59]=a16;
  a28=(a28*a05);
  if (res[0]!=0) res[0][60]=a28;
  if (res[0]!=0) res[0][61]=a29;
  a03=(a03*a06);
  if (res[0]!=0) res[0][62]=a03;
  a05=-3.1987929671703523e-03;
  a06=(a05*a06);
  if (res[0]!=0) res[0][63]=a06;
  if (res[0]!=0) res[0][64]=a10;
  a13=(a13*a07);
  if (res[0]!=0) res[0][65]=a13;
  a05=(a05*a07);
  if (res[0]!=0) res[0][66]=a05;
  a08=(a08*a07);
  if (res[0]!=0) res[0][67]=a08;
  if (res[0]!=0) res[0][68]=a26;
  if (res[0]!=0) res[0][69]=a00;
  if (res[0]!=0) res[0][70]=a17;
  if (res[0]!=0) res[0][71]=a01;
  if (res[0]!=0) res[0][72]=a25;
  if (res[0]!=0) res[0][73]=a20;
  if (res[0]!=0) res[0][74]=a24;
  if (res[0]!=0) res[0][75]=a12;
  if (res[0]!=0) res[0][76]=a02;
  if (res[0]!=0) res[0][77]=a27;
  if (res[0]!=0) res[0][78]=a04;
  if (res[0]!=0) res[0][79]=a16;
  if (res[0]!=0) res[0][80]=a28;
  if (res[0]!=0) res[0][81]=a29;
  if (res[0]!=0) res[0][82]=a03;
  if (res[0]!=0) res[0][83]=a06;
  if (res[0]!=0) res[0][84]=a10;
  if (res[0]!=0) res[0][85]=a13;
  if (res[0]!=0) res[0][86]=a05;
  if (res[0]!=0) res[0][87]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_p_global_precompute_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_p_global_precompute_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_p_global_precompute_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_p_global_precompute_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_p_global_precompute_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_p_global_precompute_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_p_global_precompute_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_p_global_precompute_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_p_global_precompute_fun_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_p_global_precompute_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_p_global_precompute_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_p_global_precompute_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_p_global_precompute_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_p_global_precompute_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_p_global_precompute_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_p_global_precompute_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_p_global_precompute_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
