/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) BlueROV_Heavy_sim_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {21, 1, 1};

/* BlueROV_Heavy_sim_expl_ode_fun:(i0[13],i1[8],i2[21])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][5] : 0;
  a03=arg[0]? arg[0][3] : 0;
  a04=casadi_sq(a03);
  a05=arg[0]? arg[0][4] : 0;
  a06=casadi_sq(a05);
  a04=(a04+a06);
  a06=casadi_sq(a02);
  a04=(a04+a06);
  a06=arg[0]? arg[0][6] : 0;
  a07=casadi_sq(a06);
  a04=(a04+a07);
  a04=sqrt(a04);
  a02=(a02/a04);
  a07=casadi_sq(a02);
  a06=(a06/a04);
  a08=casadi_sq(a06);
  a09=(a07+a08);
  a09=(a01*a09);
  a09=(a00-a09);
  a10=arg[0]? arg[0][7] : 0;
  a09=(a09*a10);
  a05=(a05/a04);
  a11=(a05*a02);
  a03=(a03/a04);
  a04=(a03*a06);
  a12=(a11-a04);
  a12=(a01*a12);
  a13=arg[0]? arg[0][8] : 0;
  a12=(a12*a13);
  a09=(a09+a12);
  a12=(a05*a06);
  a14=(a03*a02);
  a15=(a12+a14);
  a15=(a01*a15);
  a16=arg[0]? arg[0][9] : 0;
  a15=(a15*a16);
  a09=(a09+a15);
  if (res[0]!=0) res[0][0]=a09;
  a11=(a11+a04);
  a11=(a01*a11);
  a11=(a11*a10);
  a04=casadi_sq(a05);
  a08=(a04+a08);
  a08=(a01*a08);
  a08=(a00-a08);
  a08=(a08*a13);
  a11=(a11+a08);
  a08=(a02*a06);
  a09=(a03*a05);
  a15=(a08-a09);
  a15=(a01*a15);
  a15=(a15*a16);
  a11=(a11+a15);
  if (res[0]!=0) res[0][1]=a11;
  a12=(a12-a14);
  a12=(a01*a12);
  a14=(a12*a10);
  a08=(a08+a09);
  a08=(a01*a08);
  a09=(a08*a13);
  a14=(a14+a09);
  a04=(a04+a07);
  a01=(a01*a04);
  a00=(a00-a01);
  a01=(a00*a16);
  a14=(a14+a01);
  if (res[0]!=0) res[0][2]=a14;
  a14=5.0000000000000000e-01;
  a05=(a14*a05);
  a01=arg[0]? arg[0][10] : 0;
  a04=(a05*a01);
  a02=(a14*a02);
  a07=arg[0]? arg[0][11] : 0;
  a09=(a02*a07);
  a04=(a04+a09);
  a06=(a14*a06);
  a09=arg[0]? arg[0][12] : 0;
  a11=(a06*a09);
  a04=(a04+a11);
  a04=(-a04);
  if (res[0]!=0) res[0][3]=a04;
  a14=(a14*a03);
  a03=(a14*a01);
  a04=(a06*a07);
  a03=(a03-a04);
  a04=(a02*a09);
  a03=(a03+a04);
  if (res[0]!=0) res[0][4]=a03;
  a06=(a06*a01);
  a03=(a14*a07);
  a06=(a06+a03);
  a03=(a05*a09);
  a06=(a06-a03);
  if (res[0]!=0) res[0][5]=a06;
  a05=(a05*a07);
  a02=(a02*a01);
  a05=(a05-a02);
  a14=(a14*a09);
  a05=(a05+a14);
  if (res[0]!=0) res[0][6]=a05;
  a05=9.9997012697780208e-01;
  a14=7.0709999999999995e-01;
  a02=arg[1]? arg[1][0] : 0;
  a06=(a14*a02);
  a03=arg[1]? arg[1][1] : 0;
  a04=(a14*a03);
  a06=(a06+a04);
  a11=-7.0709999999999995e-01;
  a15=arg[1]? arg[1][2] : 0;
  a17=(a11*a15);
  a06=(a06+a17);
  a18=arg[1]? arg[1][3] : 0;
  a19=(a11*a18);
  a06=(a06+a19);
  a19=13.;
  a20=(a19*a16);
  a21=-1.4570000000000000e+01;
  a21=(a21*a16);
  a20=(a20+a21);
  a22=(a20*a07);
  a23=-13.;
  a24=(a23*a13);
  a25=(a24*a09);
  a22=(a22+a25);
  a06=(a06-a22);
  a22=0.;
  a25=arg[0]? arg[0][2] : 0;
  a22=(a22<a25);
  a25=1.4163572500000001e+02;
  a26=(a25*a12);
  a27=(a22?a26:0);
  a28=1.2740000000000001e+02;
  a12=(a28*a12);
  a27=(a27-a12);
  a06=(a06-a27);
  a27=-4.0300000000000002e+00;
  a29=-1.8180000000000000e+01;
  a30=casadi_fabs(a10);
  a29=(a29*a30);
  a27=(a27+a29);
  a27=(a27*a10);
  a06=(a06+a27);
  a05=(a05*a06);
  a27=-7.7294988193419290e-03;
  a29=6.0100000000000001e-02;
  a30=(a29*a02);
  a31=(a29*a03);
  a31=(a30+a31);
  a32=-6.0100000000000001e-02;
  a33=(a32*a15);
  a31=(a31+a33);
  a33=(a32*a18);
  a31=(a31+a33);
  a34=1.2000000000000000e-01;
  a35=arg[1]? arg[1][4] : 0;
  a36=(a34*a35);
  a31=(a31+a36);
  a36=-1.2000000000000000e-01;
  a37=arg[1]? arg[1][5] : 0;
  a38=(a36*a37);
  a31=(a31+a38);
  a38=arg[1]? arg[1][6] : 0;
  a39=(a34*a38);
  a31=(a31+a39);
  a39=arg[1]? arg[1][7] : 0;
  a40=(a36*a39);
  a31=(a31+a40);
  a40=(a23*a16);
  a21=(a40+a21);
  a21=(a21*a10);
  a41=(a19*a10);
  a42=-5.5000000000000000e+00;
  a42=(a42*a10);
  a43=(a41+a42);
  a43=(a43*a16);
  a21=(a21+a43);
  a43=-3.7000000000000000e-01;
  a43=(a43*a09);
  a44=(a36*a09);
  a43=(a43+a44);
  a43=(a43*a01);
  a21=(a21+a43);
  a43=2.6000000000000001e-01;
  a43=(a43*a01);
  a44=(a34*a01);
  a43=(a43+a44);
  a43=(a43*a09);
  a21=(a21+a43);
  a31=(a31-a21);
  a21=5.9999999999999998e-02;
  a21=(a21*a26);
  a21=(a22?a21:0);
  a26=-1.0999999999999999e-02;
  a12=(a26*a12);
  a21=(a21-a12);
  a31=(a31-a21);
  a21=-7.0000000000000007e-02;
  a12=-1.5500000000000000e+00;
  a43=casadi_fabs(a07);
  a43=(a12*a43);
  a43=(a21+a43);
  a43=(a43*a07);
  a31=(a31+a43);
  a27=(a27*a31);
  a05=(a05+a27);
  a27=-1.4570105274459536e-01;
  a43=7.7294988193418309e-03;
  a43=(a43*a06);
  a06=9.9997012697780219e-01;
  a06=(a06*a31);
  a43=(a43+a06);
  a06=3.4888422611106484e-01;
  a43=(a43/a06);
  a27=(a27*a43);
  a05=(a05-a27);
  a27=1.8500552667420507e+01;
  a05=(a05/a27);
  if (res[0]!=0) res[0][7]=a05;
  a05=9.9998452018563400e-01;
  a11=(a11*a02);
  a11=(a11+a04);
  a11=(a11+a17);
  a14=(a14*a18);
  a11=(a11+a14);
  a14=1.4570000000000000e+01;
  a14=(a14*a16);
  a40=(a40+a14);
  a40=(a40*a01);
  a14=5.5000000000000000e+00;
  a14=(a14*a10);
  a41=(a41+a14);
  a41=(a41*a09);
  a40=(a40+a41);
  a11=(a11-a40);
  a40=(a25*a08);
  a41=(a22?a40:0);
  a08=(a28*a08);
  a41=(a41-a08);
  a11=(a11-a41);
  a41=-6.2199999999999998e+00;
  a14=-2.1660000000000000e+01;
  a17=casadi_fabs(a13);
  a14=(a14*a17);
  a41=(a41+a14);
  a41=(a41*a13);
  a11=(a11+a41);
  a05=(a05*a11);
  a41=5.5641162018111147e-03;
  a32=(a32*a03);
  a30=(a30+a32);
  a29=(a29*a15);
  a30=(a30+a29);
  a30=(a30+a33);
  a33=-2.1800000000000000e-01;
  a29=(a33*a35);
  a30=(a30+a29);
  a33=(a33*a37);
  a30=(a30+a33);
  a33=2.1800000000000000e-01;
  a29=(a33*a38);
  a30=(a30+a29);
  a33=(a33*a39);
  a30=(a30+a33);
  a20=(a20*a13);
  a33=1.2699999999999999e+01;
  a33=(a33*a13);
  a24=(a24+a33);
  a24=(a24*a16);
  a20=(a20+a24);
  a24=3.7000000000000000e-01;
  a24=(a24*a09);
  a29=(a34*a09);
  a24=(a24+a29);
  a24=(a24*a07);
  a20=(a20+a24);
  a24=-2.3000000000000001e-01;
  a24=(a24*a07);
  a29=(a36*a07);
  a24=(a24+a29);
  a24=(a24*a09);
  a20=(a20+a24);
  a30=(a30-a20);
  a20=-5.9999999999999998e-02;
  a20=(a20*a40);
  a20=(a22?a20:0);
  a26=(a26*a08);
  a20=(a20-a26);
  a30=(a30-a20);
  a20=casadi_fabs(a01);
  a20=(a12*a20);
  a20=(a21+a20);
  a20=(a20*a01);
  a30=(a30+a20);
  a41=(a41*a30);
  a05=(a05+a41);
  a41=1.4511215054323387e-01;
  a20=-5.5641162018110731e-03;
  a20=(a20*a11);
  a11=9.9998452018563411e-01;
  a11=(a11*a30);
  a20=(a20+a11);
  a11=3.7919844905368194e-01;
  a20=(a20/a11);
  a41=(a41*a20);
  a05=(a05-a41);
  a41=2.5700397837387655e+01;
  a05=(a05/a41);
  if (res[0]!=0) res[0][8]=a05;
  a37=(a37-a35);
  a37=(a37+a38);
  a37=(a37-a39);
  a19=(a19*a13);
  a39=-1.2699999999999999e+01;
  a39=(a39*a13);
  a39=(a19+a39);
  a39=(a39*a01);
  a23=(a23*a10);
  a23=(a23+a42);
  a42=(a23*a07);
  a39=(a39+a42);
  a37=(a37-a39);
  a25=(a25*a00);
  a22=(a22?a25:0);
  a28=(a28*a00);
  a22=(a22-a28);
  a37=(a37-a22);
  a22=-5.1799999999999997e+00;
  a28=-3.6990000000000002e+01;
  a00=casadi_fabs(a16);
  a28=(a28*a00);
  a22=(a22+a28);
  a22=(a22*a16);
  a37=(a37+a22);
  a22=2.7570000000000000e+01;
  a37=(a37/a22);
  if (res[0]!=0) res[0][9]=a37;
  if (res[0]!=0) res[0][10]=a20;
  if (res[0]!=0) res[0][11]=a43;
  a43=-1.8880000000000000e-01;
  a02=(a43*a02);
  a20=1.8880000000000000e-01;
  a03=(a20*a03);
  a02=(a02+a03);
  a20=(a20*a15);
  a02=(a02+a20);
  a43=(a43*a18);
  a02=(a02+a43);
  a19=(a19+a33);
  a19=(a19*a10);
  a23=(a23*a13);
  a19=(a19+a23);
  a23=2.3000000000000001e-01;
  a23=(a23*a07);
  a34=(a34*a07);
  a23=(a23+a34);
  a23=(a23*a01);
  a19=(a19+a23);
  a23=-2.6000000000000001e-01;
  a23=(a23*a01);
  a36=(a36*a01);
  a23=(a23+a36);
  a23=(a23*a07);
  a19=(a19+a23);
  a02=(a02-a19);
  a19=casadi_fabs(a09);
  a12=(a12*a19);
  a21=(a21+a12);
  a21=(a21*a09);
  a02=(a02+a21);
  a21=4.8999999999999999e-01;
  a02=(a02/a21);
  if (res[0]!=0) res[0][12]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_sim_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_sim_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_sim_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_sim_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_sim_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_sim_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_sim_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void BlueROV_Heavy_sim_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_sim_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int BlueROV_Heavy_sim_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real BlueROV_Heavy_sim_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_sim_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* BlueROV_Heavy_sim_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_sim_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* BlueROV_Heavy_sim_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_sim_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int BlueROV_Heavy_sim_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
