/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) subcat_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {13, 1, 1};
static const casadi_int casadi_s3[3] = {25, 1, 1};

/* subcat_expl_vde_adj:(i0[17],i1[17],i2[8],i3[13])->(o0[25]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a01=5.0000000000000000e-01;
  a02=arg[0]? arg[0][12] : 0;
  a03=arg[1]? arg[1][6] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a05=arg[0]? arg[0][11] : 0;
  a06=arg[1]? arg[1][5] : 0;
  a07=(a05*a06);
  a07=(a01*a07);
  a04=(a04+a07);
  a07=arg[0]? arg[0][10] : 0;
  a08=arg[1]? arg[1][4] : 0;
  a09=(a07*a08);
  a09=(a01*a09);
  a04=(a04+a09);
  a09=arg[0]? arg[0][4] : 0;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a12=casadi_sq(a09);
  a11=(a11+a12);
  a12=arg[0]? arg[0][5] : 0;
  a13=casadi_sq(a12);
  a11=(a11+a13);
  a13=arg[0]? arg[0][6] : 0;
  a14=casadi_sq(a13);
  a11=(a11+a14);
  a11=sqrt(a11);
  a14=(a09/a11);
  a15=2.;
  a16=1.2984999999999999e+02;
  a17=-6.3483799999999998e-03;
  a18=2.0076289901626181e+00;
  a19=arg[1]? arg[1][12] : 0;
  a18=(a18*a19);
  a17=(a17*a18);
  a19=-2.0587600000000002e-03;
  a20=9.9999788076036800e-01;
  a21=4.2860814402070941e+00;
  a22=arg[1]? arg[1][10] : 0;
  a23=2.7758963993178693e-02;
  a24=7.5471538170593808e-02;
  a25=arg[1]? arg[1][8] : 0;
  a25=(a24*a25);
  a23=(a23*a25);
  a22=(a22-a23);
  a21=(a21*a22);
  a22=(a20*a21);
  a23=2.0587556369942154e-03;
  a23=(a23*a25);
  a22=(a22+a23);
  a23=(a19*a22);
  a17=(a17+a23);
  a23=-2.0587556369942176e-03;
  a23=(a23*a21);
  a25=(a20*a25);
  a23=(a23+a25);
  a17=(a17+a23);
  a17=(a16*a17);
  a25=arg[0]? arg[0][2] : 0;
  a00=(a00<a25);
  a25=143.;
  a21=-2.9999999999999999e-02;
  a21=(a21*a22);
  a21=(a21+a23);
  a21=(a25*a21);
  a21=(-a21);
  a21=(a00?a21:0);
  a17=(a17+a21);
  a21=arg[0]? arg[0][8] : 0;
  a26=arg[1]? arg[1][2] : 0;
  a27=(a21*a26);
  a17=(a17+a27);
  a17=(a15*a17);
  a27=(a14*a17);
  a04=(a04+a27);
  a27=(a12/a11);
  a28=3.3228861549042947e+00;
  a29=arg[1]? arg[1][11] : 0;
  a30=-2.7898197636908612e-02;
  a31=arg[1]? arg[1][7] : 0;
  a24=(a24*a31);
  a30=(a30*a24);
  a29=(a29-a30);
  a28=(a28*a29);
  a29=(a20*a28);
  a30=-2.0587556369942154e-03;
  a30=(a30*a24);
  a29=(a29+a30);
  a19=(a19*a29);
  a30=2.0587556369942210e-03;
  a30=(a30*a28);
  a20=(a20*a24);
  a30=(a30+a20);
  a19=(a19+a30);
  a19=(a16*a19);
  a20=2.9999999999999999e-02;
  a20=(a20*a29);
  a20=(a20+a30);
  a20=(a25*a20);
  a20=(-a20);
  a20=(a00?a20:0);
  a19=(a19+a20);
  a20=arg[0]? arg[0][7] : 0;
  a24=(a20*a26);
  a19=(a19+a24);
  a19=(a15*a19);
  a24=(a27*a19);
  a04=(a04-a24);
  a24=arg[0]? arg[0][9] : 0;
  a28=arg[1]? arg[1][1] : 0;
  a31=(a24*a28);
  a31=(a15*a31);
  a32=(a14*a31);
  a04=(a04-a32);
  a32=(a13/a11);
  a33=(a20*a28);
  a33=(a15*a33);
  a34=(a32*a33);
  a04=(a04+a34);
  a34=arg[1]? arg[1][0] : 0;
  a35=(a24*a34);
  a35=(a15*a35);
  a36=(a27*a35);
  a04=(a04+a36);
  a36=(a21*a34);
  a36=(a15*a36);
  a37=(a32*a36);
  a04=(a04-a37);
  a37=(a04/a11);
  a38=(a10+a10);
  a10=(a10/a11);
  a39=(a10/a11);
  a39=(a39*a04);
  a04=(a14/a11);
  a40=(a05*a03);
  a40=(a01*a40);
  a41=(a02*a06);
  a41=(a01*a41);
  a40=(a40-a41);
  a41=arg[1]? arg[1][3] : 0;
  a42=(a07*a41);
  a42=(a01*a42);
  a40=(a40-a42);
  a42=(a14+a14);
  a43=7.5471698113207544e-02;
  a44=arg[1]? arg[1][9] : 0;
  a43=(a43*a44);
  a25=(a25*a43);
  a25=(-a25);
  a00=(a00?a25:0);
  a25=6.3483799999999998e-03;
  a25=(a25*a29);
  a25=(a43+a25);
  a16=(a16*a25);
  a00=(a00+a16);
  a16=(a24*a26);
  a00=(a00+a16);
  a00=(a15*a00);
  a16=(a42*a00);
  a40=(a40-a16);
  a16=(a10*a17);
  a40=(a40+a16);
  a16=(a32*a19);
  a40=(a40+a16);
  a16=(a10*a31);
  a40=(a40-a16);
  a16=(a21*a28);
  a16=(a15*a16);
  a42=(a42*a16);
  a40=(a40-a42);
  a42=(a27*a33);
  a40=(a40+a42);
  a42=(a32*a35);
  a40=(a40+a42);
  a42=(a27*a36);
  a40=(a40+a42);
  a04=(a04*a40);
  a39=(a39+a04);
  a04=(a32/a11);
  a42=(a07*a06);
  a42=(a01*a42);
  a25=(a05*a08);
  a25=(a01*a25);
  a42=(a42-a25);
  a25=(a02*a41);
  a25=(a01*a25);
  a42=(a42-a25);
  a25=(a27*a17);
  a42=(a42+a25);
  a25=(a14*a19);
  a42=(a42+a25);
  a25=(a27*a31);
  a42=(a42+a25);
  a25=(a32+a32);
  a16=(a25*a16);
  a42=(a42-a16);
  a16=(a10*a33);
  a42=(a42+a16);
  a16=(a14*a35);
  a42=(a42+a16);
  a16=(a10*a36);
  a42=(a42-a16);
  a16=(a20*a34);
  a16=(a15*a16);
  a25=(a25*a16);
  a42=(a42-a25);
  a04=(a04*a42);
  a39=(a39+a04);
  a04=(a27/a11);
  a25=(a02*a08);
  a25=(a01*a25);
  a44=(a07*a03);
  a44=(a01*a44);
  a25=(a25-a44);
  a44=(a05*a41);
  a44=(a01*a44);
  a25=(a25-a44);
  a44=(a27+a27);
  a00=(a44*a00);
  a25=(a25-a00);
  a17=(a32*a17);
  a25=(a25+a17);
  a19=(a10*a19);
  a25=(a25-a19);
  a31=(a32*a31);
  a25=(a25+a31);
  a33=(a14*a33);
  a25=(a25+a33);
  a35=(a10*a35);
  a25=(a25+a35);
  a36=(a14*a36);
  a25=(a25+a36);
  a44=(a44*a16);
  a25=(a25-a44);
  a04=(a04*a25);
  a39=(a39+a04);
  a04=(a11+a11);
  a39=(a39/a04);
  a38=(a38*a39);
  a37=(a37-a38);
  if (res[0]!=0) res[0][3]=a37;
  a40=(a40/a11);
  a09=(a09+a09);
  a09=(a09*a39);
  a40=(a40-a09);
  if (res[0]!=0) res[0][4]=a40;
  a25=(a25/a11);
  a12=(a12+a12);
  a12=(a12*a39);
  a25=(a25-a12);
  if (res[0]!=0) res[0][5]=a25;
  a42=(a42/a11);
  a13=(a13+a13);
  a13=(a13*a39);
  a42=(a42-a13);
  if (res[0]!=0) res[0][6]=a42;
  a42=-3.8741300000000001e-01;
  a13=-3.0378703000000002e+01;
  a39=casadi_fabs(a20);
  a39=(a13*a39);
  a42=(a42+a39);
  a42=(a42*a30);
  a39=-1.3250000000000000e+01;
  a11=(a21*a18);
  a11=(a39*a11);
  a25=1.3250000000000000e+01;
  a12=(a25*a21);
  a40=(a12*a18);
  a11=(a11+a40);
  a40=(a05*a43);
  a40=(a39*a40);
  a11=(a11+a40);
  a40=(a02*a23);
  a40=(a25*a40);
  a11=(a11+a40);
  a40=(a24*a29);
  a40=(a25*a40);
  a11=(a11+a40);
  a40=(a39*a24);
  a09=(a40*a29);
  a11=(a11+a09);
  a42=(a42-a11);
  a11=casadi_sign(a20);
  a09=(a20*a30);
  a13=(a13*a09);
  a11=(a11*a13);
  a42=(a42+a11);
  a11=(a14*a32);
  a13=(a10*a27);
  a09=(a11-a13);
  a09=(a15*a09);
  a09=(a09*a26);
  a42=(a42+a09);
  a09=(a14*a27);
  a37=(a10*a32);
  a38=(a09+a37);
  a38=(a15*a38);
  a38=(a38*a28);
  a42=(a42+a38);
  a38=1.;
  a04=casadi_sq(a27);
  a44=casadi_sq(a32);
  a16=(a04+a44);
  a16=(a15*a16);
  a16=(a38-a16);
  a16=(a16*a34);
  a42=(a42+a16);
  if (res[0]!=0) res[0][7]=a42;
  a42=-1.3147620000000000e+00;
  a16=-3.3524884999999998e+01;
  a36=casadi_fabs(a21);
  a36=(a16*a36);
  a42=(a42+a36);
  a42=(a42*a23);
  a36=(a39*a20);
  a35=(a36*a18);
  a33=(a20*a18);
  a33=(a25*a33);
  a35=(a35+a33);
  a33=(a07*a43);
  a33=(a25*a33);
  a35=(a35+a33);
  a33=(a24*a22);
  a33=(a39*a33);
  a35=(a35+a33);
  a33=(a25*a24);
  a31=(a33*a22);
  a35=(a35+a31);
  a42=(a42-a35);
  a35=casadi_sign(a21);
  a31=(a21*a23);
  a16=(a16*a31);
  a35=(a35*a16);
  a42=(a42+a35);
  a35=(a02*a30);
  a35=(a39*a35);
  a42=(a42-a35);
  a35=(a27*a32);
  a16=(a10*a14);
  a31=(a35+a16);
  a31=(a15*a31);
  a31=(a31*a26);
  a42=(a42+a31);
  a31=casadi_sq(a14);
  a44=(a31+a44);
  a44=(a15*a44);
  a44=(a38-a44);
  a44=(a44*a28);
  a42=(a42+a44);
  a09=(a09-a37);
  a09=(a15*a09);
  a09=(a09*a34);
  a42=(a42+a09);
  if (res[0]!=0) res[0][8]=a42;
  a42=-1.1741150000000000e+02;
  a09=casadi_fabs(a24);
  a09=(a42*a09);
  a09=(a09*a43);
  a37=casadi_sign(a24);
  a24=(a24*a43);
  a42=(a42*a24);
  a37=(a37*a42);
  a09=(a09+a37);
  a37=(a39*a21);
  a42=(a37*a22);
  a09=(a09-a42);
  a21=(a21*a22);
  a21=(a25*a21);
  a09=(a09-a21);
  a21=(a07*a23);
  a21=(a39*a21);
  a09=(a09-a21);
  a21=(a25*a20);
  a42=(a21*a29);
  a09=(a09-a42);
  a20=(a20*a29);
  a39=(a39*a20);
  a09=(a09-a39);
  a39=(a05*a30);
  a25=(a25*a39);
  a09=(a09-a25);
  a31=(a31+a04);
  a31=(a15*a31);
  a38=(a38-a31);
  a38=(a38*a26);
  a09=(a09+a38);
  a35=(a35-a16);
  a35=(a15*a35);
  a35=(a35*a28);
  a09=(a09+a35);
  a11=(a11+a13);
  a15=(a15*a11);
  a15=(a15*a34);
  a09=(a09+a15);
  if (res[0]!=0) res[0][9]=a09;
  a09=-1.3861200000000001e-01;
  a15=-5.0396799999999997e-01;
  a34=casadi_fabs(a07);
  a34=(a15*a34);
  a09=(a09+a34);
  a09=(a09*a22);
  a34=-2.3336999999999999e-01;
  a11=(a05*a18);
  a11=(a34*a11);
  a13=3.0099999999999999e-01;
  a35=(a13*a05);
  a35=(a35*a18);
  a11=(a11+a35);
  a12=(a12*a43);
  a11=(a11+a12);
  a09=(a09-a11);
  a11=casadi_sign(a07);
  a12=(a07*a22);
  a15=(a15*a12);
  a11=(a11*a15);
  a09=(a09+a11);
  a40=(a40*a23);
  a09=(a09-a40);
  a40=2.3336999999999999e-01;
  a11=(a02*a29);
  a11=(a40*a11);
  a09=(a09-a11);
  a11=-4.9809999999999999e-01;
  a15=(a11*a02);
  a15=(a15*a29);
  a09=(a09-a15);
  a27=(a01*a27);
  a15=(a27*a03);
  a09=(a09-a15);
  a32=(a01*a32);
  a15=(a32*a06);
  a09=(a09+a15);
  a10=(a01*a10);
  a15=(a10*a08);
  a09=(a09+a15);
  a01=(a01*a14);
  a14=(a01*a41);
  a09=(a09-a14);
  if (res[0]!=0) res[0][10]=a09;
  a09=-6.0195600000000005e-01;
  a14=casadi_fabs(a05);
  a14=(a09*a14);
  a14=(a14*a29);
  a34=(a34*a07);
  a34=(a34*a18);
  a15=(a07*a18);
  a13=(a13*a15);
  a34=(a34+a13);
  a36=(a36*a43);
  a34=(a34+a36);
  a36=-3.0099999999999999e-01;
  a13=(a02*a22);
  a13=(a36*a13);
  a34=(a34+a13);
  a13=4.9809999999999999e-01;
  a15=(a13*a02);
  a15=(a15*a22);
  a34=(a34+a15);
  a14=(a14-a34);
  a34=casadi_sign(a05);
  a15=(a05*a29);
  a09=(a09*a15);
  a34=(a34*a09);
  a14=(a14+a34);
  a33=(a33*a30);
  a14=(a14-a33);
  a33=(a01*a03);
  a14=(a14+a33);
  a33=(a10*a06);
  a14=(a14+a33);
  a33=(a32*a08);
  a14=(a14-a33);
  a33=(a27*a41);
  a14=(a14-a33);
  if (res[0]!=0) res[0][11]=a14;
  a14=-7.0000000000000007e-02;
  a33=-2.0000000000000001e-01;
  a34=casadi_fabs(a02);
  a34=(a33*a34);
  a14=(a14+a34);
  a14=(a14*a18);
  a34=casadi_sign(a02);
  a02=(a02*a18);
  a33=(a33*a02);
  a34=(a34*a33);
  a14=(a14+a34);
  a36=(a36*a05);
  a36=(a36*a22);
  a14=(a14-a36);
  a05=(a05*a22);
  a13=(a13*a05);
  a14=(a14-a13);
  a21=(a21*a23);
  a14=(a14-a21);
  a40=(a40*a07);
  a40=(a40*a29);
  a14=(a14-a40);
  a07=(a07*a29);
  a11=(a11*a07);
  a14=(a14-a11);
  a37=(a37*a30);
  a14=(a14-a37);
  a10=(a10*a03);
  a14=(a14+a10);
  a01=(a01*a06);
  a14=(a14-a01);
  a27=(a27*a08);
  a14=(a14+a27);
  a32=(a32*a41);
  a14=(a14-a32);
  if (res[0]!=0) res[0][12]=a14;
  a14=arg[0]? arg[0][13] : 0;
  a32=cos(a14);
  a41=arg[2]? arg[2][0] : 0;
  a27=2.6015899999999997e-01;
  a18=(a27*a18);
  a08=(a41*a18);
  a08=(a32*a08);
  a14=sin(a14);
  a01=(a41*a43);
  a01=(a14*a01);
  a08=(a08-a01);
  a27=(a27*a22);
  a22=(a41*a27);
  a22=(a14*a22);
  a08=(a08-a22);
  a22=2.0148428999999999e-02;
  a22=(a22*a29);
  a01=(a41*a22);
  a01=(a32*a01);
  a08=(a08+a01);
  a01=1.8775000000000000e-01;
  a01=(a01*a29);
  a06=(a41*a01);
  a06=(a14*a06);
  a08=(a08+a06);
  a41=(a41*a30);
  a41=(a32*a41);
  a08=(a08-a41);
  if (res[0]!=0) res[0][13]=a08;
  a08=arg[0]? arg[0][14] : 0;
  a41=cos(a08);
  a06=arg[2]? arg[2][1] : 0;
  a10=(a06*a18);
  a10=(a41*a10);
  a08=sin(a08);
  a03=(a06*a43);
  a03=(a08*a03);
  a10=(a10-a03);
  a03=(a06*a27);
  a03=(a08*a03);
  a10=(a10-a03);
  a03=(a06*a22);
  a03=(a41*a03);
  a10=(a10+a03);
  a03=1.8275000000000000e-01;
  a03=(a03*a29);
  a29=(a06*a03);
  a29=(a08*a29);
  a10=(a10-a29);
  a06=(a06*a30);
  a06=(a41*a06);
  a10=(a10-a06);
  if (res[0]!=0) res[0][14]=a10;
  a10=arg[0]? arg[0][15] : 0;
  a06=sin(a10);
  a29=arg[2]? arg[2][2] : 0;
  a37=(a29*a27);
  a37=(a06*a37);
  a10=cos(a10);
  a11=(a29*a18);
  a11=(a10*a11);
  a07=(a29*a43);
  a07=(a06*a07);
  a11=(a11+a07);
  a37=(a37-a11);
  a11=(a29*a22);
  a11=(a10*a11);
  a37=(a37+a11);
  a11=(a29*a03);
  a11=(a06*a11);
  a37=(a37-a11);
  a29=(a29*a30);
  a29=(a10*a29);
  a37=(a37-a29);
  if (res[0]!=0) res[0][15]=a37;
  a37=arg[0]? arg[0][16] : 0;
  a29=sin(a37);
  a11=arg[2]? arg[2][3] : 0;
  a07=(a11*a27);
  a07=(a29*a07);
  a37=cos(a37);
  a40=(a11*a18);
  a40=(a37*a40);
  a21=(a11*a43);
  a21=(a29*a21);
  a40=(a40+a21);
  a07=(a07-a40);
  a40=(a11*a22);
  a40=(a37*a40);
  a07=(a07+a40);
  a40=(a11*a01);
  a40=(a29*a40);
  a07=(a07+a40);
  a11=(a11*a30);
  a11=(a37*a11);
  a07=(a07-a11);
  if (res[0]!=0) res[0][16]=a07;
  a07=(a14*a18);
  a11=(a32*a43);
  a07=(a07+a11);
  a11=(a32*a27);
  a07=(a07+a11);
  a11=(a14*a22);
  a07=(a07+a11);
  a32=(a32*a01);
  a07=(a07-a32);
  a14=(a14*a30);
  a07=(a07-a14);
  if (res[0]!=0) res[0][17]=a07;
  a07=(a08*a18);
  a14=(a41*a43);
  a07=(a07+a14);
  a14=(a41*a27);
  a07=(a07+a14);
  a14=(a08*a22);
  a07=(a07+a14);
  a41=(a41*a03);
  a07=(a07+a41);
  a08=(a08*a30);
  a07=(a07-a08);
  if (res[0]!=0) res[0][18]=a07;
  a07=(a10*a43);
  a08=(a06*a18);
  a07=(a07-a08);
  a08=(a10*a27);
  a07=(a07-a08);
  a08=(a06*a22);
  a07=(a07+a08);
  a10=(a10*a03);
  a07=(a07+a10);
  a06=(a06*a30);
  a07=(a07-a06);
  if (res[0]!=0) res[0][19]=a07;
  a43=(a37*a43);
  a18=(a29*a18);
  a43=(a43-a18);
  a27=(a37*a27);
  a43=(a43-a27);
  a22=(a29*a22);
  a43=(a43+a22);
  a37=(a37*a01);
  a43=(a43-a37);
  a29=(a29*a30);
  a43=(a43-a29);
  if (res[0]!=0) res[0][20]=a43;
  a43=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][21]=a43;
  a43=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][22]=a43;
  a43=arg[1]? arg[1][15] : 0;
  if (res[0]!=0) res[0][23]=a43;
  a43=arg[1]? arg[1][16] : 0;
  if (res[0]!=0) res[0][24]=a43;
  return 0;
}

CASADI_SYMBOL_EXPORT int subcat_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int subcat_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int subcat_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void subcat_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int subcat_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void subcat_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void subcat_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void subcat_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int subcat_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int subcat_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real subcat_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* subcat_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* subcat_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* subcat_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* subcat_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int subcat_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int subcat_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
