/* This file was automatically generated by CasADi 3.6.7+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) subcat_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {17, 1, 1};
static const casadi_int casadi_s1[3] = {8, 1, 1};
static const casadi_int casadi_s2[3] = {13, 1, 1};

/* subcat_expl_ode_fun:(i0[17],i1[8],i2[13])->(o0[17]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  a00=1.;
  a01=2.;
  a02=arg[0]? arg[0][5] : 0;
  a03=arg[0]? arg[0][3] : 0;
  a04=casadi_sq(a03);
  a05=arg[0]? arg[0][4] : 0;
  a06=casadi_sq(a05);
  a04=(a04+a06);
  a06=casadi_sq(a02);
  a04=(a04+a06);
  a06=arg[0]? arg[0][6] : 0;
  a07=casadi_sq(a06);
  a04=(a04+a07);
  a04=sqrt(a04);
  a02=(a02/a04);
  a07=casadi_sq(a02);
  a06=(a06/a04);
  a08=casadi_sq(a06);
  a09=(a07+a08);
  a09=(a01*a09);
  a09=(a00-a09);
  a10=arg[0]? arg[0][7] : 0;
  a09=(a09*a10);
  a05=(a05/a04);
  a11=(a05*a02);
  a03=(a03/a04);
  a04=(a03*a06);
  a12=(a11-a04);
  a12=(a01*a12);
  a13=arg[0]? arg[0][8] : 0;
  a12=(a12*a13);
  a09=(a09+a12);
  a12=(a05*a06);
  a14=(a03*a02);
  a15=(a12+a14);
  a15=(a01*a15);
  a16=arg[0]? arg[0][9] : 0;
  a15=(a15*a16);
  a09=(a09+a15);
  if (res[0]!=0) res[0][0]=a09;
  a11=(a11+a04);
  a11=(a01*a11);
  a11=(a11*a10);
  a04=casadi_sq(a05);
  a08=(a04+a08);
  a08=(a01*a08);
  a08=(a00-a08);
  a08=(a08*a13);
  a11=(a11+a08);
  a08=(a02*a06);
  a09=(a03*a05);
  a15=(a08-a09);
  a15=(a01*a15);
  a15=(a15*a16);
  a11=(a11+a15);
  if (res[0]!=0) res[0][1]=a11;
  a12=(a12-a14);
  a12=(a01*a12);
  a14=(a12*a10);
  a08=(a08+a09);
  a08=(a01*a08);
  a09=(a08*a13);
  a14=(a14+a09);
  a04=(a04+a07);
  a01=(a01*a04);
  a00=(a00-a01);
  a01=(a00*a16);
  a14=(a14+a01);
  if (res[0]!=0) res[0][2]=a14;
  a14=5.0000000000000000e-01;
  a05=(a14*a05);
  a01=arg[0]? arg[0][10] : 0;
  a04=(a05*a01);
  a02=(a14*a02);
  a07=arg[0]? arg[0][11] : 0;
  a09=(a02*a07);
  a04=(a04+a09);
  a06=(a14*a06);
  a09=arg[0]? arg[0][12] : 0;
  a11=(a06*a09);
  a04=(a04+a11);
  a04=(-a04);
  if (res[0]!=0) res[0][3]=a04;
  a14=(a14*a03);
  a03=(a14*a01);
  a04=(a06*a07);
  a03=(a03-a04);
  a04=(a02*a09);
  a03=(a03+a04);
  if (res[0]!=0) res[0][4]=a03;
  a06=(a06*a01);
  a03=(a14*a07);
  a06=(a06+a03);
  a03=(a05*a09);
  a06=(a06-a03);
  if (res[0]!=0) res[0][5]=a06;
  a05=(a05*a07);
  a02=(a02*a01);
  a05=(a05-a02);
  a14=(a14*a09);
  a05=(a05+a14);
  if (res[0]!=0) res[0][6]=a05;
  a05=9.9999788076036800e-01;
  a14=-3.8741300000000001e-01;
  a02=-3.0378703000000002e+01;
  a06=casadi_fabs(a10);
  a02=(a02*a06);
  a14=(a14+a02);
  a14=(a14*a10);
  a02=arg[0]? arg[0][13] : 0;
  a06=sin(a02);
  a03=arg[1]? arg[1][0] : 0;
  a06=(a06*a03);
  a04=arg[0]? arg[0][14] : 0;
  a11=sin(a04);
  a15=arg[1]? arg[1][1] : 0;
  a11=(a11*a15);
  a17=(a06+a11);
  a18=arg[0]? arg[0][15] : 0;
  a19=sin(a18);
  a20=arg[1]? arg[1][2] : 0;
  a19=(a19*a20);
  a21=(a17+a19);
  a22=arg[0]? arg[0][16] : 0;
  a23=sin(a22);
  a24=arg[1]? arg[1][3] : 0;
  a23=(a23*a24);
  a21=(a21+a23);
  a25=1.3250000000000000e+01;
  a26=(a25*a16);
  a27=(a26*a07);
  a28=-1.3250000000000000e+01;
  a29=(a28*a13);
  a30=(a29*a09);
  a27=(a27+a30);
  a21=(a21+a27);
  a27=0.;
  a30=arg[0]? arg[0][2] : 0;
  a27=(a27<a30);
  a30=143.;
  a31=(a30*a12);
  a32=(a27?a31:0);
  a33=1.2984999999999999e+02;
  a12=(a33*a12);
  a32=(a32-a12);
  a21=(a21+a32);
  a14=(a14-a21);
  a21=(a05*a14);
  a32=-2.0587556369942154e-03;
  a34=1.8275000000000000e-01;
  a04=cos(a04);
  a04=(a04*a15);
  a15=(a34*a04);
  a35=1.8775000000000000e-01;
  a02=cos(a02);
  a02=(a02*a03);
  a03=(a35*a02);
  a15=(a15-a03);
  a18=cos(a18);
  a18=(a18*a20);
  a34=(a34*a18);
  a15=(a15+a34);
  a22=cos(a22);
  a22=(a22*a24);
  a35=(a35*a22);
  a15=(a15-a35);
  a35=2.0148428999999999e-02;
  a06=(a35*a06);
  a15=(a15+a06);
  a11=(a35*a11);
  a15=(a15+a11);
  a11=(a35*a19);
  a15=(a15+a11);
  a35=(a35*a23);
  a15=(a15+a35);
  a35=(a28*a16);
  a11=(a35*a10);
  a06=(a25*a10);
  a24=(a06*a16);
  a11=(a11+a24);
  a24=-4.9809999999999999e-01;
  a24=(a24*a09);
  a24=(a24*a01);
  a11=(a11+a24);
  a24=2.3336999999999999e-01;
  a24=(a24*a01);
  a24=(a24*a09);
  a11=(a11+a24);
  a15=(a15-a11);
  a11=2.9999999999999999e-02;
  a11=(a11*a31);
  a11=(a27?a11:0);
  a31=6.3483799999999998e-03;
  a24=(a33*a00);
  a31=(a31*a24);
  a34=-2.0587600000000002e-03;
  a12=(a34*a12);
  a31=(a31+a12);
  a11=(a11-a31);
  a15=(a15-a11);
  a11=-6.0195600000000005e-01;
  a31=casadi_fabs(a07);
  a11=(a11*a31);
  a11=(a11*a07);
  a15=(a15+a11);
  a32=(a32*a15);
  a21=(a21+a32);
  a32=-2.7898197636908612e-02;
  a11=2.0587556369942210e-03;
  a11=(a11*a14);
  a15=(a05*a15);
  a11=(a11+a15);
  a15=3.0094320219911413e-01;
  a11=(a11/a15);
  a32=(a32*a11);
  a21=(a21-a32);
  a32=1.3250028079984633e+01;
  a21=(a21/a32);
  if (res[0]!=0) res[0][7]=a21;
  a21=-1.3147620000000000e+00;
  a15=-3.3524884999999998e+01;
  a14=casadi_fabs(a13);
  a15=(a15*a14);
  a21=(a21+a15);
  a21=(a21*a13);
  a35=(a35*a01);
  a06=(a06*a09);
  a35=(a35+a06);
  a06=(a30*a08);
  a15=(a27?a06:0);
  a33=(a33*a08);
  a15=(a15-a33);
  a35=(a35+a15);
  a21=(a21-a35);
  a35=(a05*a21);
  a15=2.0587556369942154e-03;
  a08=2.6015899999999997e-01;
  a02=(a02+a04);
  a04=(a02-a18);
  a04=(a04-a22);
  a04=(a08*a04);
  a26=(a26*a13);
  a29=(a29*a16);
  a26=(a26+a29);
  a29=4.9809999999999999e-01;
  a14=(a29*a09);
  a14=(a14*a07);
  a26=(a26+a14);
  a14=-3.0099999999999999e-01;
  a14=(a14*a07);
  a14=(a14*a09);
  a26=(a26+a14);
  a04=(a04-a26);
  a26=-2.9999999999999999e-02;
  a26=(a26*a06);
  a26=(a27?a26:0);
  a34=(a34*a33);
  a26=(a26-a34);
  a04=(a04-a26);
  a26=-1.3861200000000001e-01;
  a34=-5.0396799999999997e-01;
  a06=casadi_fabs(a01);
  a34=(a34*a06);
  a26=(a26+a34);
  a26=(a26*a01);
  a04=(a04+a26);
  a15=(a15*a04);
  a35=(a35+a15);
  a15=2.7758963993178693e-02;
  a26=-2.0587556369942176e-03;
  a26=(a26*a21);
  a05=(a05*a04);
  a26=(a26+a05);
  a05=2.3331334552329044e-01;
  a26=(a26/a05);
  a15=(a15*a26);
  a35=(a35-a15);
  a35=(a35/a32);
  if (res[0]!=0) res[0][8]=a35;
  a02=(a02+a18);
  a02=(a02+a22);
  a22=(a25*a13);
  a18=(a22*a01);
  a28=(a28*a10);
  a35=(a28*a07);
  a18=(a18+a35);
  a02=(a02-a18);
  a30=(a30*a00);
  a27=(a27?a30:0);
  a27=(a27-a24);
  a02=(a02-a27);
  a27=-1.1741150000000000e+02;
  a24=casadi_fabs(a16);
  a27=(a27*a24);
  a27=(a27*a16);
  a02=(a02+a27);
  a02=(a02/a25);
  if (res[0]!=0) res[0][9]=a02;
  if (res[0]!=0) res[0][10]=a26;
  if (res[0]!=0) res[0][11]=a11;
  a17=(a17-a19);
  a17=(a17-a23);
  a08=(a08*a17);
  a22=(a22*a10);
  a28=(a28*a13);
  a22=(a22+a28);
  a28=3.0099999999999999e-01;
  a28=(a28*a07);
  a28=(a28*a01);
  a22=(a22+a28);
  a28=-2.3336999999999999e-01;
  a28=(a28*a01);
  a28=(a28*a07);
  a22=(a22+a28);
  a08=(a08-a22);
  a22=-6.3483799999999998e-03;
  a22=(a22*a33);
  a08=(a08+a22);
  a22=-7.0000000000000007e-02;
  a33=-2.0000000000000001e-01;
  a28=casadi_fabs(a09);
  a33=(a33*a28);
  a22=(a22+a33);
  a22=(a22*a09);
  a08=(a08+a22);
  a08=(a08/a29);
  if (res[0]!=0) res[0][12]=a08;
  a08=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][13]=a08;
  a08=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][14]=a08;
  a08=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][15]=a08;
  a08=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][16]=a08;
  return 0;
}

CASADI_SYMBOL_EXPORT int subcat_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int subcat_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int subcat_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void subcat_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int subcat_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void subcat_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void subcat_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void subcat_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int subcat_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int subcat_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real subcat_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* subcat_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* subcat_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* subcat_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* subcat_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int subcat_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int subcat_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
